### ISSUE TITLE
puppet not found on Windows VM when installed from MSI

### ISSUE THREAD

**Issue by ringods** [WinRb/vagrant-windows#101]
Environment:
- vagrant 1.3.1
- vagrant-windows 1.2.1
- vagrant-librarian-puppet-plugin 0.1.2

I have a Win2008R2 VM with Puppet 3.3.0 installed from the official MSI. When trying to `vagrant provision` the VM, I get this error:

```
#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">The term 'puppet' is not recognized as the name of a cmdlet, function, script f_x000D__x000A_</S><S S="Error">ile, or operable program. Check the spelling of the name, or if a path was incl_x000D__x000A_</S><S S="Error">uded, verify that the path is correct and try again._x000D__x000A_</S><S S="Error">At line:38 char:51_x000D__x000A_</S><S S="Error">+ cd /tmp/vagrant-puppet/manifests; if($?) {  puppet &lt;&lt;&lt;&lt;  apply --modulepath '_x000D__x000A_</S><S S="Error">/ProgramData/PuppetLabs/puppet/etc/modules;/tmp/vagrant-puppet/modules-0' init._x000D__x000A_</S><S S="Error">pp }_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: (puppet:String) [], CommandNotFo _x000D__x000A_</S><S S="Error">   undException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
```

The MSI installs the Puppet Agent as a Windows service, but if you want to run it interactively, you have to open a `Start Command Prompt with Puppet` shell. It starts a shell with the required paths correctly set up. The paths are not added system wide.

**Comment by sneal** [comment]
Can you send a gist of your Vagrantfile?

**Comment by ferventcoder** [comment]
We don't add puppet to the path with the msi installer. I'm not completely
sure why, let me check with @joshcooper.

On Tuesday, September 24, 2013, Shawn Neal wrote:

> Can you send a gist of your Vagrantfile?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WinRb/vagrant-windows/issues/101#issuecomment-25047497
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ringods** [comment]
Here is my Vagrantfile:

https://gist.github.com/ringods/6695889

**Comment by sneal** [comment]
Vagrant and vagrant-windows make the assumption that "puppet" is in your PATH. We could update vagrant-windows to be more accommodating and default to the default install location, but I'd prefer not to do that until I have the time to rewrite the provisioners to be Windows specific rather than the monkey patches mess they are today.

This has pointed out a bug in the WinRMCommunicator. The execute/sudo method should be throwing an exception when 'which puppet' fails. Currently it only returns an exit status of 1, but the Vagrant puppet provisioner excepts an exception to be thrown. Added #106 for this.

**Comment by ferventcoder** [comment]
As a link back to track our progress on putting puppet on the PATH - http://projects.puppetlabs.com/issues/22700

This would not apply until the 3.4 release though, so perhaps some support there earlier would be good.

**Comment by ferventcoder** [comment]
Here is the workaround for this:
- In your vagrant file, put in a shell provisioner - https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/boxes/win7x64pro-vagrant/Vagrantfile#L23
- Make a call to something to set the install directory to your path permanently - https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/boxes/win7x64pro-vagrant/shell/main.cmd#L8
- Ensure that the path is only set once - https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/boxes/win7x64pro-vagrant/shell/InstallPuppet.ps1#L27-L40

**Comment by ringods** [comment]
Rob, thanks a lot for the fully functional workaround!

**Comment by sneal** [comment]
:+1: @ferventcoder

**Comment by ringods** [comment]
@ferventcoder I tested with Puppet 3.3.1-rc3 and it works without the workaround of adding Puppet to the system path myself. Tnx!

**Comment by ferventcoder** [comment]
@ringods I guess we got that one in a little early. :)

**Comment by jdub** [comment]
This appears to have regressed with Puppet 3.6.2 and 3.7.1. Testing other versions at the moment.

**Comment by ferventcoder** [comment]
@jdub We had this report recently, can you verify or reproduce? https://tickets.puppetlabs.com/browse/PUP-3471

cc @joshcooper @Iristyle

**Comment by jdub** [comment]
Sorry, I was so pleased to have found a relevant bug report, I barely paid attention to the project I was reporting it against. :-) Will pop over there now.

**Comment by ferventcoder** [comment]
@jdub I am not sure yet, but I think your case may be slightly different. See the bug report.

**Comment by iDVB** [comment]
I'm still seeing this issue in the latest version of https://github.com/ferventcoder/vagrant-windows-puppet and using **Vagrant 1.7.2**

Things seem to bomb out on the installing puppet step of the `win7x64pro-vagrant` Vagrantfile
 ![Installing Puppet](http://goo.gl/YaaKmz)

Now I'm still very new to Vagrant, and it seems to me that the latest version of Vagrant prompts you to remove and not use vagrant-windows. Can anyone point me in the right direction here?

D

**Comment by cregev** [comment]
Is there any ETA for this feature? ?

**Comment by ferventcoder** [comment]
@cregev vagrant-windows is deprecated. What feature are you looking for an ETA on?
