### ISSUE TITLE
Winrm 503 during box booting

### ISSUE THREAD

**Issue by sstarcher** [WinRb/vagrant-windows#103]
Vagrant 1.2.4-1.2.7 with Vagrant-Windows 1.2.1
If I test winrm using gem winrm through my localhost port that has been forwarded I can execute commands on the windows machine, but vagrant never gets past the box booting.

On Vagrant versions prior to 1.2.4 I get a error with the monkey patch that was being applied and the code does not even get to booting the box and waiting for winrm.

The basebox is Windows 2008 Server R2.

**Comment by sneal** [comment]
Can you send a gist of the debug vagrant output?

**Comment by sneal** [comment]
Did you get this working? Can you try vagrant-windows 1.2.2?

**Comment by sneal** [comment]
Closing this for now. If you're still having problems please re-open.
