### ISSUE TITLE
configuration "config.winrm.hostname" is not used

### ISSUE THREAD

**Issue by behrica** [WinRb/vagrant-windows#104]
I have the situation that the connection via knife to the VM fails with a "501" error, if I run "vagrant up" againsta windows virtualbox with correct wirm configuration.

I could debug it down to a problem between using "127.0.0.1" versus "localhost".

The connection with "knife -m localhost" does work, while "knife - m 127.0.0.1" does not work. Even though localhost gets resolved to 127.0.0.1...

So it should work by setting "config.winrm.hostname" to "localhost", but it still does not.
I saw in debug output that configuration parameter is not used for creating the connection, it still logs here:

 @logger.info("Attempting to connect to WinRM...")
        @logger.info("  - Host: #{@host}")
        @logger.info("  - Port: #{@port}")
        @logger.info("  - Username: #{@username}")

that is uses "127.0.0.1" instead of "localhost".

It seems that the code takes the host to connect from the ssh_config and NOT from 
"config.winrm.hostname".

This means for me that the config parameter "config.winrm.hostname" does not do anything.
Is this correct ?

If I hardcode the @host variable to "localhost" in WinRmShell.initialize

everything works.

**Comment by sneal** [comment]
Fixed in 1.2.2

**Comment by lsim** [comment]
Any news on when the 1.2.2 will be available via 'vagrant plugin install vagrant-windows'? It appears I am currently block by this issue.

If I absolutely have to, I will build from source, but as I am not a ruby developer, I don't have any of the prerequisites on my system, so it would incur a bit of unwanted overhead.

Thanks for working on this plugin, by the way. I was very happy to find it.

**Comment by sneal** [comment]
Monday. I wasn't able to cut the gem before I went out of town.

**Comment by sneal** [comment]
@lsim 1.2.2 has been released.

**Comment by lsim** [comment]
Works nicely. Thanks!
