### ISSUE TITLE
Virtual box never finishes opening Windows 7 GUI

### ISSUE THREAD

**Issue by DrCord** [WinRb/vagrant-windows#105]
I really appreciate you making a plugin that allows windows Vagrant boxes with virtual box. It seems like it almost is working, but not quite. I went through the install instructions and the Windows7 machine boots to a screenshot of the login screen and sits there, never giving me an actual window to control the virtual machine. In case that isn't clear: the way I can tell it is running is through the screenshot and startup noise, but I don't have an actual window to control/interface with the machine in question. Thanks for the help!
![vb-vagrant](https://f.cloud.github.com/assets/306243/1219574/a59c3faa-26cd-11e3-9718-b27eef11e7e5.png)

**Comment by sneal** [comment]
Add this to your Vagrantfile

``` ruby
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
```

**Comment by DrCord** [comment]
works perfectly, thanks for the fix and the super quick response!
