### ISSUE TITLE
Can't get vagrant-windows to install on Linux host

### ISSUE THREAD

**Issue by cdmoye** [WinRb/vagrant-windows#117]
I'm running RHEL 6, and Vagant 1.3.5. Here's what I'm trying:

vagrant plugin install vagrant-windows

Here's what I'm getting back:

http://pastebin.com/Hknir0z7

**Comment by raulbrito** [comment]
Hi,

Not sure if it's the root cause for your error, but vagrant-windows only supports vagrant until v1.2, so you need to downgrade. Check here: https://github.com/WinRb/vagrant-windows#installation . Sad but true :|

**Comment by cdmoye** [comment]
It could easily be related to that. However, I tried it with older vagrants last week (1.1 and 1.2) and had similar issues.

**Comment by sneal** [comment]
@raulbrito Vagrant 1.1 through 1.3.5 is supported with the latest plugin gem. I'm running Vagrant 1.3.5 with vagrant-windows 1.2.2.

**Comment by sneal** [comment]
@cdmoye I assume you're using the Vagrant 1.3.5 rpm package? I haven't tried vagrant-windows on RHL yet, but I would like too.

**Comment by raulbrito** [comment]
@sneal wow, great news! not sure how i've missed that one. time for some upgrading..

**Comment by sneal** [comment]
@raulbrito I just updated the readme, you're right in that it wasn't clear.

**Comment by raulbrito** [comment]
@sneal :thumbsup:

**Comment by cdmoye** [comment]
Yes. That's the package I'm using.

----- Reply message -----

**Comment by cdmoye** [comment]
Sorry, wrong button :)

**Comment by cdmoye** [comment]
BTW, if it's useful, here is a pastebin of the compile.log referenced in the earlier error: http://pastebin.com/y6QPHeCV

**Comment by cdmoye** [comment]
Hm. I just stood up a brand new Fedora 18 box and have run a total of two commands on it (after a yum update, and downloading vagrant 1.3.5):

sudo rpm -Uvh vagrant_1.3.5_x86_64.rpm
vagrant plugin install vagrant-windows

I get the same error messages as on the RHEL 6 box. The exact same ones. Am I missing something somewhere? Seems like I must be.

**Comment by sneal** [comment]
It appears to fail compiling Nokogiri's native extensions, perhaps [this](http://nokogiri.org/tutorials/installing_nokogiri.html) will help.

**Comment by cdmoye** [comment]
Nokogiri does seem to be the issue. First, I can't install it without ruby-doc. I fixed that, but the bigger part is this:

ERROR:  Error installing nokogiri:
    nokogiri requires Ruby version >= 1.9.2.

Vagrant's built-in ruby is 1.9.1. I'm trying to work around that now, but rvm is giving me fits. Installing and setting the ruby version via sudo doesn't seem to stick for subsequent calls to sudo :).

**Comment by cdmoye** [comment]
So, I've played a lot with things. Installing newer versions of ruby from source, trying to install nokogiri from gem install, things like that. However, nothing has really affected anything.

In the second pastebin that I posted (http://pastebin.com/y6QPHeCV), the compile.log contains what I'm sure is a clue: 

./.libs/libxml2.so: undefined reference to `gzopen64'

gzopen64 is supposedly in zlib. I have zlib installed, so I'm not sure why it can't find it.

To try a little harder, I downloaded the latest zlib source (1.2.8) and think I installed it... I ran ./configure and sudo make install from within the directory where I unpacked it. After that, same results. I'm still sad.

I am confused even further by the fact that I seem to be the only one unable to install the plugin (at least on RHEL and Fedora--I admit that I haven't tried Ubuntu or anything else, yet). Even from a brand new Fedora 18 build, the same problem is there.

**Comment by cdmoye** [comment]
So, I think I've narrowed it down to a problem getting libxml2 to compile. If I download the 2.8.0 source directly from xmlsoft.org and compile/install it like so:

wget ftp://xmlsoft.org/libxml2/libxml2-2.8.0.tar.gz
tar zxvf libxml2-2.8.0.tar.gz 
cd libxml2-2.8.0
./configure
sudo make install

I get that same error:

  CCLD   xmllint
./.libs/libxml2.so: undefined reference to `gzopen64'
collect2: ld returned 1 exit status

So clearly something is missing somewhere. As I mentioned in the previous comment, I (think) I have the lastest zlib installed, so I'm not sure where it's looking for it.

At this point, I'd almost consent that it's not a vagrant-windows issue, but it seems like the package should be self-sufficient and not require whatever it is I'm missing to be done externally. And again, I've seen it in 2 different environments (1 totally clean). Is anyone else able to reproduce/see the same behavior?

**Comment by cdmoye** [comment]
I've now tried it on Ubuntu 13.10 (clean install) and have the same issue. So, I guess the question is, how is everyone else making it work? :)

**Comment by stonith** [comment]
I get similar issues on ubuntu 13.10. However, on my Windows and OSX host I don't have these problems installing vagrant-windows.

**Comment by sneal** [comment]
Out of curiosity can you plain old 'gem install vagrant-windows'?

**Comment by cdmoye** [comment]
Looks to be the same result: http://pastebin.com/528W8At3

Something that nokogiri needs just isn't present by default. Who needs to parse XML anyhow? ;)

**Comment by sneal** [comment]
I tried installing the gem on an old Ubuntu 11.10 VM (that didn't have Ruby yet on it) and it installed fine after I installed Ruby and the Ruby devkit.

```
sudo apt-get install ruby1.9.1
sudo apt-get install ruby1.9.1-dev
sudo gem install vagrant-windows
```

The only obvious differences is my VM has Ruby 1.9.1. and does not have RVM installed. I'll try a newer Ubuntu version later today.

**Comment by cdmoye** [comment]
Interesting. Using those steps, it installs fine on ubuntu 13.10. Let me try it with Ruby 1.9.1 on my RHEL  box (I was trying with ruby 2.0.0).

**Comment by cdmoye** [comment]
Still no love on RHEL 6 with ruby 1.9.1

ERROR:  Error installing vagrant-windows:
    nokogiri requires Ruby version >= 1.9.2.

I tried it with 1.9.2 and 1.9.3 all to no avail as well. At this point, I'm starting to assume that RHEL 6 is just too jacked up to support vagrant-windows, which rules it out in our space (likely along with windows guests via vagrant  because I can't figure them out any other way) since, annoyingly enough, our dev boxes are all RHEL 6 Workstation.

I'm curious, though. "/opt/vagrant/embedded/bin/ruby -v" returns 1.9.3. However, /opt/vagrant/embedded/lib/ruby looks like it's set up for 1.9.1. I wonder if this is why it's getting nokogiri in the first place instead of using using the one in /opt/vagrant/embedded/lib/ruby/gems/1.9.1/gems/nokogiri-1.6.0.

**Comment by tendervittles** [comment]
I filed a duplicate issue on this same problem. I didn't notice this thread.

To fix just remove the extra } character at the end of the lines mentioned here: 

https://github.com/mitchellh/vagrant/issues/2427

**Comment by cdmoye** [comment]
Ding ding ding! We have a winner! Thanks!

**Comment by cdmoye** [comment]
I'm closing this since it seems to be an issue in the vagrant script.
