### ISSUE TITLE
Vagrant Up error - Method Missing

### ISSUE THREAD

**Issue by ndrluis** [WinRb/vagrant-windows#12]
Error
https://gist.github.com/4493503

Vagrantfile
https://gist.github.com/4493520

**Comment by heymishy** [comment]
you need to install the winrm package.

gem install winrm

**Comment by ndrluis** [comment]
The winrm is installed.

vagrant (1.0.5)
vagrant-vbguest (0.4.0)
vagrant-windows (0.1.2)
winrm (1.1.2)

**Comment by pmorton** [comment]
Sorry for taking so long to engage. Are you running this as part of a bundle? The error seems to suggest the the plugin is not loading automatically.
