### ISSUE TITLE
vagrant provision hang when running .exe in the batch file using shell provisioner

### ISSUE THREAD

**Issue by nopower0** [WinRb/vagrant-windows#127]
I'm using Vagrant 1.2.7 + vagrant-windows 1.2.3.
When I run .exe program inside the batch file, provisioning will hang no matter I'm running up, provision or reload. Simple commands are fine, for example, "xcopy A B" works fine, but "start C:\" will make it hang there.

**Comment by sneal** [comment]
Add `-NoNewWindow` to the end of your command, for example:

```
config.vm.provision :shell, inline: 'start C:\Windows\Microsoft.NET\Framework64\v2.0.50727\aspnet_regiis.exe -NoNewWindow'
```

See [Start-Process](http://technet.microsoft.com/en-us/library/hh849848.aspx) for more information.
