### ISSUE TITLE
Base box configuration described in wiki is not correct for Windows 2008 R2 and WinRM 1.1

### ISSUE THREAD

**Issue by patatepartie** [WinRb/vagrant-windows#128]
By default the http port for WinRM 1.1 is 80. To change it:

``` shell
netsh firewall add portopening TCP 5985 "Port 5985"
winrm set winrm/config/listener?Address=*+Transport=HTTP @{Port="5985"}
```

And powershell needs to be enabled:
http://www.tech-recipes.com/rx/2521/windows_server_2008_install_windows_powershell/

**Comment by johnjelinek** [comment]
Would not setting this cause Win2008r2 to hang at `Waiting for machine to boot. This may take a few minutes...`?

**Comment by patatepartie** [comment]
Actually it times out after a (long) while, but yes, it hangs on that sentence for a while.
If you enable vagrant's logs you can see that it actually tries the request multiple times.

**Comment by sneal** [comment]
Fixed in 1.3.0

**Comment by johnjelinek** [comment]
What is the commit for this fix?

**Comment by sneal** [comment]
@johnjelinek The fix was an update to the readme.

**Comment by patatepartie** [comment]
Thanks for that and for the great plugin, Shawn.
