### ISSUE TITLE
possible performance improvement in chef solo provisioner

### ISSUE THREAD

**Issue by kashook** [WinRb/vagrant-windows#130]
The chef solo provisioner is executed in a scheduled task in the VM.  I noticed that the priority of the task is pretty low.  I wonder if increasing the priority would speed up the chef runs. Valid priority values can be found [here](http://msdn.microsoft.com/en-us/library/aa383512.aspx).  The current priority being used is 7.  I haven't done any experimentation at all.  I just wanted to get the idea out there.

**Comment by sneal** [comment]
Good suggestion.

**Comment by sneal** [comment]
Fixed in 1.3.0
