### ISSUE TITLE
Timeout when running vagrant up on Windows 7 host

### ISSUE THREAD

**Issue by dabide** [WinRb/vagrant-windows#132]
When I run `vagrant up`, it eventually times out while detecting if the OS has booted. The VM boots fine.

Here's the debug log: http://pastebin.com/76uxrDYY

**Comment by dabide** [comment]
I found the reason: I had set the network connection profile to Public in stead of Home or Work, thus making the WinRM configuration fail. (Next time, I should pay closer attention to the error messages...)

Perhaps this should be in the README?

**Comment by sneal** [comment]
Mind sending a PR with an updated readme?

**Comment by dabide** [comment]
Network connections that are added through Vagrantfile are also automatically set to Public in Windows 7. A solution is described in pull request #170.
