### ISSUE TITLE
Chef fails creating directory in synced folder

### ISSUE THREAD

**Issue by pghalliday** [WinRb/vagrant-windows#133]
I am syncing a host directory and have a chef recipe that needs to create a sub directory in it. The recipe works fine if the directory created is within the file system of the guest but when I try to create the directory in the synced folder I get the following error from the `get_named_security_info` Win32 API call. Any thoughts?

```
[2013-11-13T10:21:08+01:00] FATAL: Chef::Exceptions::Win32APIError: directory[C:\Development\GADGET_LIB] (opentv-build-legacy::default line 49) had an error: Chef::Exceptions::Win32APIError: Incorrect function.
get_named_security_info(C:\Development\GADGET_LIB, SE_FILE_OBJECT, 7)---- Begin
Win32 API output ----
System Error Code: 1
System Error Message: Incorrect function.
---- End Win32 API output ----
```

The directory itself is created, so I guess the failure is just after that.

This is using
- `vagrant 1.3.5`
- `vagrant-windows 1.2.3`
- `vagrant-berkshelf 1.3.4`
- `Chef 11.8.0`
- `VirtualBox 4.3.2`
- `Windows 7` for both guest and host

**Comment by pghalliday** [comment]
I also noticed that I get a similar issue with the version of gcc I have to use which runs into an `Invalid request code` error accessing files in the mounted directory.

However I have noticed that the way the directory is mounted under windows with VirtualBox is to create a network share and then create a shortcut to that network share in the local file system.

I also noted that I don't run into the GCC error if I mount the network share normally and then run my build in there. I think it is the shortcut mechanism that is causing the problem. Although I have not yet tested if mounting the share at a drive letter and creating directories there will workaround the chef problem too.

**Comment by sneal** [comment]
Seems to be the same issue as https://github.com/WinRb/vagrant-windows/issues/112

I'd like to see this get fixed, but I'm not sure why this is happening.

**Comment by pghalliday** [comment]
Yes I think you're right. I was wondering if mounting the share to a drive letter first and then linking to that would workaround the problem. I'm going to look into how you create the link (I presume that is done by this plugin)

**Comment by pghalliday** [comment]
Unfortunately I can't get this to work using `mklink` to a remote directory even after mounting it to a drive letter. I tried the `/J` and `/H` options too but obviously that did not work as they only work for links to the same volume. I tried replacing all my forward slashes with back slashes in case that was tripping things up, but no joy.

As far as I can see this will not work while using symbolic links to network shares.

The only option left as far as I can see would be to add an option to mount shares at drive letters instead of (or as well as) local directory paths.

In the meantime I can work around the `gcc` problem by mounting them manually once the guest is up and running.
This unfortunately doesn't really help when provisioning with chef.

**Comment by sneal** [comment]
That's unfortunate, but I appreciate the info on this.

**Comment by pghalliday** [comment]
You can see my work in progress here:

https://github.com/pghalliday/vagrant-windows/tree/mount-share-with-drive-letter

I can quite easily mount the share with a drive letter using a new `drive_letter` option for `synced_folder`. However I then ran into a problem that mapped drives are not available to scheduled tasks unless you remap them (http://www.tgrmn.com/web/kb/item93.htm).

So just to test, I tried hardcoding a `net use` call in the scheduled powershell script for chef-solo but ran into the same problem again :(

```
[2013-11-14T17:34:43+01:00] FATAL: Chef::Exceptions::Win32APIError: directory[X:\GADGET_LIB] (opentv-build-legacy::default line 49) had an error: Chef::Exceptions::Win32APIError: Incorrect function.
get_named_security_info(X:\GADGET_LIB, SE_FILE_OBJECT, 7)---- Begin Win32 API output ----
System Error Code: 1
System Error Message: Incorrect function.
---- End Win32 API output ----
```

So although this fixes my gcc error it doesn't help with chef :((

I'm going to see if this is a known issue with chef on windows but so far my searches have proved fruitless.

**Comment by sneal** [comment]
This sucks, but perhaps we'll have more options in the future with newer versions of Vagrant.

**Comment by chiriaev** [comment]
Guys, Hi. I found a solution a few months ago. It's working all right. Please see https://github.com/klarna/vagrant-cloudstack/issues/15. For RSYNC I used https://www.itefix.no/i2/cwrsync. I guess that also applies to https://github.com/WinRb/vagrant-windows/issues/180

Regards, Andrei
