### ISSUE TITLE
Cannot execute download script after installing the vagrant windows plugins

### ISSUE THREAD

**Issue by kithokit** [WinRb/vagrant-windows#137]
/opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/communicators/ssh/communicator.rb:120:in `initialize': No such file or directory - http://localhost.com/myscript.sh
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/communicators/ssh/communicator.rb:120:in`open'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/communicators/ssh/communicator.rb:120:in `block in upload'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/communicators/ssh/communicator.rb:389:in`block in scp_connect'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/communicators/ssh/communicator.rb:154:in `connect'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/communicators/ssh/communicator.rb:387:in`scp_connect'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/communicators/ssh/communicator.rb:114:in `upload'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/provisioners/shell/provisioner.rb:22:in`block (2 levels) in provision'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/provisioners/shell/provisioner.rb:16:in `tap'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/provisioners/shell/provisioner.rb:16:in`block in provision'
        from /home/kithokit/.vagrant.d/gems/gems/vagrant-windows-1.3.0/lib/vagrant-windows/monkey_patches/plugins/provisioners/shell/provisioner.rb:69:in `with_script_file'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/provisioners/shell/provisioner.rb:14:in`provision'
        from /home/kithokit/.vagrant.d/gems/gems/vagrant-windows-1.3.0/lib/vagrant-windows/monkey_patches/plugins/provisioners/shell/provisioner.rb:15:in `call'
        from /home/kithokit/.vagrant.d/gems/gems/vagrant-windows-1.3.0/lib/vagrant-windows/monkey_patches/plugins/provisioners/shell/provisioner.rb:15:in`block in class:Provisioner'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/builtin/provision.rb:74:in `run_provisioner'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/builtin/provision.rb:62:in`block in call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/builtin/provision.rb:58:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/builtin/provision.rb:58:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/providers/virtualbox/action/set_name.rb:47:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in`call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'

**Comment by sneal** [comment]
Thanks for reporting this, yet another reason monkey patches are evil.

**Comment by sneal** [comment]
Vagrant added support for remote scripts, the old vagrant-windows monkey patch is missing this new change
https://github.com/mitchellh/vagrant/commit/47594036b4d926c84b25345a8e64528b295b1673#diff-3d7fe3ea7d7abbe66ea2fcfe344c69f6

**Comment by kithokit** [comment]
Hi, Will you have a fix for this later on?

**Comment by sneal** [comment]
I'll modify the monkey patch to fix this for now in 1.3.1. Should be out in a couple days.

I'm not sure it'll support downloadable scripts for Windows, but it'll at least avoid breaking non-Windows guests who use them.

**Comment by kithokit** [comment]
That's great. Many thanks!

**Comment by sneal** [comment]
Fixed in 1.3.1
