### ISSUE TITLE
Vagrant Windows 1.3.0 Hangs on Vagrant Up

### ISSUE THREAD

**Issue by johnjelinek** [WinRb/vagrant-windows#139]
I'm using this template https://github.com/jedi4ever/veewee/tree/master/templates/windows-2008R2-serverstandard-amd64 to build a base box (it uses cygwin+ssh). When I vagrant up this box, it hangs here:

```
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'windows-2008R2-serverstandard-amd64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
```

Here's my Vagrantfile:

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "windows-2008R2-serverstandard-amd64"
  config.vm.box_url = "./windows-2008R2-serverstandard-amd64.box"
  config.vm.guest = :windows
  config.vm.boot_timeout = 10000
end
```

Am I missing something?

**Comment by johnjelinek** [comment]
lol, I was missing port forwarding for winrm. :facepalm:

**Comment by sneal** [comment]
On the other hand it would be nice if the WinRM port was auto forwarded like the SSH port - even better if the plugin would find a free port if the default port was already in use.

**Comment by ferventcoder** [comment]
+10000 to finding a free port and autoforwarding!!!!

On Thursday, November 21, 2013, Shawn Neal wrote:

> On the other hand it would be nice if the WinRM port was auto forwarded
> like the SSH port - even better if the plugin would find a free port if the
> default port was already in use.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WinRb/vagrant-windows/issues/139#issuecomment-29042012
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder
