### ISSUE TITLE
The chef powershell_script resource fails on vagrant virtual box windows 2012 machine

### ISSUE THREAD

**Issue by dawilliams** [WinRb/vagrant-windows#142]
Hello,

I've got a simple powershell_script resource that runs fine outside of a vagrant controled virtual box machine running Windows Server 2012.  However on vagrant machine it fails with "STDERR: Thread failed to start." error.  Below is the powershell script

powershell_script "Install Microsoft KB2828842" do
  code <<-EOH
  dism /Online /add-package /PackagePath:"#{Chef::Config[:file_cache_path]}/KB2828842/Windows8-RT-KB2828842-v2-x64.cab" /NoRestart /quiet
  if ($LASTEXITCODE -eq 0 -or $LASTEXITCODE -eq 3010) {$LASTEXITCODE = 0} 
  EOH
end

**Comment by dawilliams** [comment]
I don't this is just a vagrant issue though it happens on Vagrant all the time while only occasionally on other machines.

**Comment by sneal** [comment]
This doesn't sound like a plugin issue, I'm going to close this.

**Comment by dawilliams** [comment]
Sorry about that.  At first it was just happening in vagrant.  Thanks!
