### ISSUE TITLE
WinRM 3.0 (from WMF 4.0) doesn't seem to work

### ISSUE THREAD

**Issue by ferventcoder** [WinRb/vagrant-windows#148]
I saw issue #79 addressed a workaround, but it doesn't appear that things are quite working with WMF 4.0 installed.

I started with 1.2.3 this morning and worked up to 1.3.2 and it's hanging on connection to WinRM:

```
DEBUG winrmfinder: Searching for WinRM port: 5985
DEBUG winrmshell: initializing WinRMShell
DEBUG winrmshell: powershell executing:
hostname
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 192.168.78.146
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
```

It can start and stop the machine, but it won't communicate with it.

This is with a VmWare Fusion 5.0 box.

Now, if I run this guy, everything starts to work. Perhaps this should be added to the documentation?

```
winrm set winrm/config/service @{EnableCompatibilityHttpListener = "true"}
```

Thoughts?

**Comment by ferventcoder** [comment]
That may have been too quick to state...still seems stuck at `[default] Waiting for the VM to finish booting...`.

`vagrant provision` works without the priorly stated configuration, but since it hung at waiting for the VM to boot, it never mounted the folders necessary for the provisioner to run successfully.

**Comment by sneal** [comment]
I was hoping to have a chance to try this today, but AFAIK this _should_ work.

**Comment by ferventcoder** [comment]
Anything further on this?

**Comment by sneal** [comment]
I can reproduce this on Win2k8R2SP1 using VBox. I haven't had time to dig into this beyond that.

**Comment by sneal** [comment]
This plugin is no longer maintained since Vagrant natively supports Windows guests. If you have a Vagrant issue you need to ask the Vagrant mailing list or file a GitHub issue on [Vagrant core](https://github.com/mitchellh/vagrant).
