### ISSUE TITLE
Plugin should autocorrect the winrm port if the default 5985 is not available

### ISSUE THREAD

**Issue by sneal** [WinRb/vagrant-windows#149]
Having to manually select a free port on the host wastes time. This should work like core vagrant does WRT to the SSH port.

**Comment by ferventcoder** [comment]
I thought this issue was already logged last week

**Comment by sneal** [comment]
Maybe you were thinking of this [comment](https://github.com/klarna/vagrant-cloudstack/issues/15#issuecomment-29663688)?

**Comment by ferventcoder** [comment]
Unfortunately that wasn't it. I +1'd it. It must have been on another repository but I was thinking it was here. It was just a comment somewhere near the bottom of a different issue. No worries... :)

**Comment by ferventcoder** [comment]
Found it - https://github.com/WinRb/vagrant-windows/issues/139#issuecomment-29043056

**Comment by sneal** [comment]
We should be using this in our Vagrantfiles

```
config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
```

The autocorrect piece is already supported in vagrant-windows - I just misunderstood how it worked.

**Comment by ferventcoder** [comment]
Wat?! NICE

**Comment by ferventcoder** [comment]
I wonder why that isn't the default (`auto_correct: true`)?
