### ISSUE TITLE
Failed to load the vagrant-windows plugin in Vagrant 1.4.0

### ISSUE THREAD

**Issue by johnjelinek** [WinRb/vagrant-windows#151]
I uninstalled and reinstalled vagrant-windows as Vagrant 1.4.0 directed. Now whenever I run a vagrant up or vagrant ssh, I see:

`Failed to load the "vagrant-windows" plugin. View logs for more details.`

I don't know where the logs are stored.

**Comment by sneal** [comment]
I see this too, so don't worry about the logs yet.

**Comment by mkubenka** [comment]
Vagrant 1.4 start using new SyncedFolders middleware.

Try this fix (sorry I'm not Ruby developer):
https://github.com/mkubenka/vagrant-windows/commit/4820fdad0078563216dec19041575a497b265eb2

**Comment by sneal** [comment]
Fixed in 1.4.0
