### ISSUE TITLE
ERROR: Logon failure: unknown user name or bad password

### ISSUE THREAD

**Issue by xiaoxinyang** [WinRb/vagrant-windows#152]
I saw this error when I tried to do chef-solo provision.

After some investigation, I find that C:\tmp\vagrant-chef-1\cheftask.ps1 double-quotes the windows password:
$ grep pass  ./lib/vagrant-windows/scripts/cheftask.ps1.erb
schtasks /create /tn "chef-solo" /xml "<%= options[:chef_task_xml] %>" /ru "<%= options[:user] %>" /rp "<%= options[:pass] %>

If the password contains a "$", it will lead to this "Logon failure" error because powershell treats "$..." as a variable which normally results in an empty string.

So, the password should be single-quoted.

**Comment by sneal** [comment]
Fixed in 1.4.0
