### ISSUE TITLE
vagrant plugin install fails with vagrant 1.4.2

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/vagrant-windows#159]
https://gist.github.com/lmayorga1980/8224831

**Comment by lmayorga1980** [comment]
Seems like is an error with nokogiri 1.6.1 and OSX

**Comment by sneal** [comment]
What other plugins do you have installed?

**Comment by lmayorga1980** [comment]
0 plugins installed. It seems that I have an issue with nokogiri 1.6.1 and the grep BSD version in OSX Mavericks. 

http://stackoverflow.com/questions/20890808/install-nokogiri-1-6-1-under-ruby-2-0-0p353-rvm-based-installation-fails-osx

**Comment by sneal** [comment]
Seems like an environment issue rather than a vagrant-windows issue.
