### ISSUE TITLE
SQL Server cookbook fails to install through Vagrant

### ISSUE THREAD

**Issue by sneal** [WinRb/vagrant-windows#16]
I've created this issue in order to fix [COOK-1172](http://tickets.opscode.com/browse/COOK-1172).

There are essentially two issues with installing SQL Server through vagrant-windows, or more specifically through WinRM:
1. The guest VM group policy needs to be relaxed around WinRM console limits on memory. This can easily be addressed via a group policy change on the VM.
2. The chef-solo process needs to run under the context of an administrative user that can delegate credentials.

The latter needs to be patched in vagrant-windows. My current thinking is to wrap the chef-solo command in a PowerShell script that spawns chef-solo via System.Diagnostics.Process providing the vagrant credentials.

```
function ps-runas ([String] $cmd, [String] $arguments)
{
  $secpasswd = ConvertTo-SecureString "vagrant" -AsPlainText -Force

  $process = New-Object System.Diagnostics.Process
  $setup = $process.StartInfo
  $setup.FileName = $cmd
  $setup.Arguments = $arguments
  $setup.UserName = "vagrant"
  $setup.Password = $secpasswd
  $setup.Verb = "runas"
  $setup.UseShellExecute = $false
  $setup.RedirectStandardError = $true
  $setup.RedirectStandardOutput = $true
  $setup.RedirectStandardInput = $false

  # Hook into the standard output and error stream events
  $errEvent = Register-ObjectEvent -InputObj $process `
    -Event "ErrorDataReceived" `
    -Action `
    {
        param
        (
            [System.Object] $sender,
            [System.Diagnostics.DataReceivedEventArgs] $e
        )
        Write-Host $e.Data
    }
  $outEvent = Register-ObjectEvent -InputObj $process `
    -Event "OutputDataReceived" `
    -Action `
    {
        param
        (
            [System.Object] $sender,
            [System.Diagnostics.DataReceivedEventArgs] $e
        )
        Write-Host $e.Data
    }

  Write-Host "ps-runas starting: $cmd"

  if (!$process.Start())
  {
    Write-Error "Failed to start $cmd"
  }

  $process.BeginOutputReadLine()
  $process.BeginErrorReadLine()

  # Wait until process exit
  $process.WaitForExit()

  $process.CancelOutputRead()
  $process.CancelErrorRead()
  $process.Close()
}
```

I still need to figure out how to pass the appropriate credentials instead of hardcoding them and I also need to figure out if I should spawn yet another PowerShell process to invoke chef-solo, because the command given from Vagrant isn't really Windows or System.Diagnostics.Process friendly (e.g. chef-solo -c /tmp/vagrant-chef-1/solo.rb -j /tmp/vagrant-chef-1/dna.json).

I also wonder does it make sense to wrap every command in this ps-runas wrapper or only the chef-solo command?

**Comment by pmorton** [comment]
Closing in favor of the issue with the PR
