### ISSUE TITLE
vagrant vm.network private_network setting does not work

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/vagrant-windows#165]
Hi,

I tried to use the **vm.network :private_network, ip:xx.xx.xx.xx** setting on my vagrant file but it doesn't seem to work even when using `vagrant reload`.

vagrant-windows: 1.5.0
vagrant: 1.4.2
virtualbox: 4.3.6

I don't think there is a way to set the specific ip address unless i am missing something.

**Comment by ferventcoder** [comment]
I'm not sure vagrant reload works with vagrant-windows (but I'm not the authority).

**Comment by lmayorga1980** [comment]
Did you try setting a static ip address using this setting?  I guess i can call the provisioner and call an inline or batch script

**Comment by lmayorga1980** [comment]
I just had to restart the guest. This works fine
