### ISSUE TITLE
Having issues with port forwarding using windows. vagrant seems to map 3389 (RDP) regardless of configuration.

### ISSUE THREAD

**Issue by ghost** [WinRb/vagrant-windows#171]
Hi, 

I am having issues with port forward collisions. It seems to map 3389 first regardless of what I specify in the configuration. Although it does do the mapping last , but the first port causes a collision with local running RDP service. I am also trying to get a multi machine environment setup. 

Host: windows 8 
Guest: windows 2012 (not r2) 
Vagrant: 1.4.3
vagrant-windows: 1.5.1

<config>

Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.network :forwarded_port, guest: 3389, host: 3377 , id: "rdp", auto_correct: true
    web.vm.box_url = "http://localhost/boxes/windows_2012_virtualbox.box"
    web.vm.box = "win2012"
    web.winrm.username = "vagrant"
    web.winrm.password = "vagrant"  
    web.vm.guest = :windows  
    web.windows.halt_timeout = 15
    web.berkshelf.enabled = true
    web.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    web.vm.provision :chef_solo do |chef|
      chef.log_level         = :info
      chef.add_recipe ("demo.rest.service::default")
    end
  end
end

</config>

<output>

[web] Clearing any previously set network interfaces...
[web] Preparing network interfaces based on configuration...
[web] Forwarding ports...
[web] -- 22 => 2222 (adapter 1)
[web] -- 3389 => 3389 (adapter 1)
[web] -- 5985 => 5985 (adapter 1)
[web] -- 3389 => 3377 (adapter 1)
[web] Running 'pre-boot' VM customizations...
[web] Booting VM...

</output

Any help appreciated. 

O.

**Comment by sneal** [comment]
I only see one forwarded port in your configuration. You must have another Vagrantfile in a parent directory or have modified the default Vagrantfile in the Vagrant installer or something. Vagrant doesn't forward any ports itself outside SSH (22 -> 2222).

See the Vagrant docs under [Vagrantfile](http://docs.vagrantup.com/v2/vagrantfile/index.html) for more info

**Comment by ghost** [comment]
Thanks for this, it seems there was port forwarding configured in the Vagrantfile in the .box 
Appreciate the pointer.

**Comment by ferventcoder** [comment]
Seems like someone is in trouble for making assumptions on the part of their vagrant box users. The box itself should have a very lean vagrantfile with nothing more than the mac address - https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/baseboxes/win2008r2-x64-vbox4216-nocm/Vagrantfile#L5
