### ISSUE TITLE
provisioner.rb:76:in `unlink': No such file or directory

### ISSUE THREAD

**Issue by oknoproblem** [WinRb/vagrant-windows#172]
When i'm trying to start shell provisioner i'm geting such error all the time:

[default] Running provisioner: shell...
C:/Users/user/.vagrant.d/gems/gems/vagrant-windows-1.5.1/lib/vagrant-windows/m
onkey_patches/plugins/provisioners/shell/provisioner.rb:76:in `unlink': No such
file or directory - C:/Users/user/.vagrant.d/tmp/5b747331-ced7-455a-bc5b-a6f78
a370123-remote-script.bat (Errno::ENOENT)
        from C:/Users/user/.vagrant.d/gems/gems/vagrant-windows-1.5.1/lib/vagr
ant-windows/monkey_patches/plugins/provisioners/shell/provisioner.rb:76:in`dele
te'
....

I dont understand why, but looks like 5b747331-ced7-455a-bc5b-a6f78
a370123-remote-script.bat was not created in coresponding tmp folder, so it also was not executed.

Any suggestions?

**Comment by oknoproblem** [comment]
found why.

my Vagrant version is 1.2.7 and your plugin version is 1.5.1...
you guyts should do something to dont let "vagrant plugin install vagrant-window" command on old vagrant version to install latest pluging.

**Comment by sneal** [comment]
Are you using a downloaded shell script? I don't think older versions of Vagrant support that.

vagrant-windows versions don't align with Vagrant versions, they're independent. Vagrant-windows 1.5.1 _should_ work on all versions of Vagrant all the way back to 1.1.

**Comment by oknoproblem** [comment]
my vagrant file is:
    config.windows.halt_timeout = 15
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    config.vm.guest = :windows
    config.vm.network :forwarded_port, guest: 5985, host: 5685
    config.vm.network :forwarded_port, guest: 5986, host: 5686
    config.vm.network :forwarded_port, guest: 8080, host: 5687
    config.vm.network :forwarded_port, guest: 1521, host: 5688
    config.winrm.port = 5685
    config.windows.set_work_network = true
    config.vm.network :private_network, ip: "192.168.33.33"
    config.vm.provision :shell, :path => "provision.bat"

and when i'm doing "vagrant provision" on old version of vagrant (1.2.7) with new version of "vagrant-windows" i'm getting "No such file or directory" error in method "with_windows_script_file" on line 76 provisioner.rb file.

begin
              Vagrant::Util::Downloader.new(config.path, download_path).download!
              yield download_path
            ensure
              download_path.delete
            end

everything was fine in older plugin version.

So, yes, i'm sure they are not compatible.

For now i have Vagrant 1.4.0 and 1.5.1 plugin version and everything is fine

**Comment by oknoproblem** [comment]
main reason (i'm think so) is that Vagrant version 1.2.7 does not understand this construction:
Vagrant::Util::Downloader.new(config.path, download_path).download!

**Comment by sneal** [comment]
Closing since I don't think many people are going to run across this.
