### ISSUE TITLE
Use Schedule.Service to run Chef Task

### ISSUE THREAD

**Issue by ramarnat** [WinRb/vagrant-windows#174]
@sneal 

I wrote a recipe called wintask about a year ago for the same reason vagrant-windows creates a scheduled task - timeouts etc. for use with my windows recipes that I was running using knife winrm. But I used the Windows api wrapper in ruby. I am wondering if there would be any benefit to integrating that here, so the calls to create the task are native/api driven rather than via shell. 

It supports creating the task under a specified user, and specifying additional configuration information around the task. 

I am happy to take a stab at doing the integration into this plugin if there is any interest. ~~I have not uploaded the wintask to github, but I can do that too.~~

https://github.com/ramarnat/wintask

**Comment by sneal** [comment]
Do you know if that works from PowerShell in Windows Server 2008, I thought it required newer OS versions.

I've also started rewriting the way vagrant-windows handles scheduling the task, using the COM object instead of shelling out. https://github.com/WinRb/vagrant-windows/blob/run-all-provisioners-elevated/lib/vagrant-windows/scripts/elevated_shell.ps1.erb

**Comment by ramarnat** [comment]
It should, I am using com and Schedule.Service as well, but using the Windows ruby library. I uploaded the recipe to github for you to peruse. 

https://github.com/ramarnat/wintask

**Comment by ramarnat** [comment]
I was somewhat of a noob with ruby when I wrote the recipe, some of the dependencies with nokogiri can probably be removed and use erb instead.

**Comment by sneal** [comment]
Thanks for sharing, what you did is pretty neat - especially useful for bootstrapping new Windows nodes via knife.

I plan on focusing my attention on Vagrant core, so I will probably not make any significant changes to this plugin if I can avoid it.

**Comment by ramarnat** [comment]
no worries.
