### ISSUE TITLE
Vagrant 1.5 warnings

### ISSUE THREAD

**Issue by petems** [WinRb/vagrant-windows#177]
```
WARNING: Could not load IOV methods. Check your GSSAPI C library for an update
WARNING: Could not load AEAD methods. Check your GSSAPI C library for an update
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
```

```
$vagrant --version
Vagrant 1.5.0
```

**Comment by svpernova09** [comment]
`WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1`

Vagrant 1.5 & 1.5.1

**Comment by dmjio** [comment]
+1 I get this too. Vagrant 1.5.1, OSX 10.9.2

```
WARNING: Could not load IOV methods. Check your GSSAPI C library for an update
WARNING: Could not load AEAD methods. Check your GSSAPI C library for an update
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
Bringing machine 'windows' up with 'virtualbox' provider...
```

**Comment by nickchappell** [comment]
I'm getting the same warnings as @dmjio, same Vagrant and OS X version.

**Comment by andrewdeandrade** [comment]
I'm not a ruby guy but trying my best to investigate this further and near as I can tell, this is a WinRM issue, which is a gem that vagrant-windows relies on. Looking more closely, the version of savon used by winrm is way way way out of date. (0.9.5 vs 2.3.3). I'm guessing that either savon or its old dependency wasabi which load nokogiri are responsible in some way. Problem is that I can't get the tests to run in WinRM to try and update the savon gem, but without tests I don't know enough to debug this.

**Comment by jgeorge300** [comment]
The solution for this SO question (http://stackoverflow.com/questions/13884588/chef-knife-gives-gssapi-c-library-warning) hides the first 2 warning messages.

**Comment by dmjio** [comment]
commenting out the warnings hardly seems like a solution

**Comment by dmjio** [comment]
But it's that annoying I guess I'll do it

**Comment by andrewdeandrade** [comment]
Huh? Commenting out the first two warnings still doesn't solve the breaking problem involving nokogiri. For whatever reason I can't find anyway to either (1) make the vagrant-windows or winrm gems to load libxml2 2.8.0 that nokogiri 1.6.1 now is statically built with or (2) install vagrant-windows in a way that overrides the version that nokogiri is statically linked to so that it uses libxml2 2.9.1. None of the solutions out there for solving the libxml2 nokogiri issues like setting bundler config build flags work since vagrant is using embedded ruby instead of a system ruby or an rbenv or rvm ruby.

**Comment by dmjio** [comment]
@malandrew, same w/ me it didn't work

**Comment by jen20** [comment]
+1, I'm also seeing this.

```
$ vagrant --version
Vagrant 1.5.1
$ vagrant
WARNING: Could not load IOV methods. Check your GSSAPI C library for an update
WARNING: Could not load AEAD methods. Check your GSSAPI C library for an update
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
Usage: vagrant [options] <command> [<args>]
...
```

**Comment by cmluciano** [comment]
This also seems to happen in vagrant 1.5.2

```
$ vagrant -v
Vagrant 1.5.2
$ vagrant
WARNING: Could not load IOV methods. Check your GSSAPI C library for an update
WARNING: Could not load AEAD methods. Check your GSSAPI C library for an update
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
```

**Comment by sneal** [comment]
This is addressed in Vagrant core https://github.com/mitchellh/vagrant/pull/3393. No more annoying, but harmless warnings.

**Comment by andrewdeandrade** [comment]
@sneal the GSSAPI warnings are harmless but the libxml2 warning for nokogiri is not. AFAICT it's related to the savon gem in the winrm gem which IIRC is being deprecated in the next major version of the WinRM gem, but it doesn't look like there is much development activity in that gem.

**Comment by andrewdeandrade** [comment]
@sneal looking at the vagrant fix, is the immediate loading of the GSSAPI stuff responsible for loading the wrong version of libxml?
