### ISSUE TITLE
solo.rb file_cache_path is not a Windows friendly path

### ISSUE THREAD

**Issue by sneal** [WinRb/vagrant-windows#18]
The path specified in the solo.rb generated by vagrant is not Windows friendly and causes problems for some applications.

Actual path: /tmp/vagrant-chef-1
Expected path: c:\tmp\vagrant-chef-1

More specifically this causes problems with the community SQL Server cookbook. This cookbook generates a configuration file in the chef file cache which it passes off to setup.exe. The path it generates is missing the drive letter (as in the example above) and fails the setup.

```
config_file_path = win_friendly_path(File.join(Chef::Config[:file_cache_path], "ConfigurationFile.ini"))
```

Note: None of the other paths in the solo.rb file are Windows friendly either, however they're not causing any specific issues at the moment that I have encountered.

**Comment by pmorton** [comment]
@sneal Any thoughts on how to address this?

**Comment by sneal** [comment]
Since we now monkey patch the run_chef_solo method, I suppose it wouldn't be too hard to wrap all the paths with a method that makes them windows friendly.

**Comment by sneal** [comment]
Fixed in vagrant-windows1.2

**Comment by lewisthompson** [comment]
I'm still seeing issues with the sql_server cookbook with vagrant-windows 1.3.0.  The path is \var\chef\cache\ConfigurationFile.ini.  However I am using "config.vm.provision "chef_client"" not solo, so perhaps that is my issue.

**Comment by ianrossi** [comment]
I can confirm that I am also seeing this issue with the sql_server cookbook on vagrant-windows 1.5.1. @sneal It looks like you reopened this. Do you know of an interim fix?

**Comment by sneal** [comment]
Try adding a Windows style file_cache_path to your Chef config

```
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe 'dotnetframework'
    chef.file_cache_path = 'c:/chef/cache'
  end
```

**Comment by ianrossi** [comment]
@sneal Thanks! I was scouring the Vagrant docs for that setting, but I should have gone with my gut and tried it. :) Thanks again.

**Comment by sneal** [comment]
This plugin is no longer maintained since Vagrant natively supports Windows guests. If you have a Vagrant issue you need to ask the Vagrant mailing list or file a GitHub issue on [Vagrant core](https://github.com/mitchellh/vagrant).
