### ISSUE TITLE
Vagrant-login 0.9.0 not found

### ISSUE THREAD

**Issue by andrewrlee** [WinRb/vagrant-windows#193]
Hi,

I had an issue with the vagrant-login module not being found when I tried to install the vagrant-windows module. 

I managed to get round this by installing the latest version of vagrant-login  (version 1.0.1) first.

``` shell
C:\data\vagrant\windows>vagrant plugin install vagrant-windows
Installing the 'vagrant-windows' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Net::HTTPNotFound: No gems found matching "vagrant-login" "0.9.0" nil

C:\data\vagrant\windows>vagrant plugin install vagrant-login
Installing the 'vagrant-login' plugin. This can take a few minutes...
Installed the plugin 'vagrant-login (1.0.1)'!

C:\data\vagrant\windows>vagrant plugin install vagrant-windows
Installing the 'vagrant-windows' plugin. This can take a few minutes...
Installed the plugin 'vagrant-windows (1.6.0)'!

```

**Comment by sneal** [comment]
Before attempting to install vagrant-windows the first time, did you have vagrant-login 0.9.0 installed or 1.0.1?

**Comment by andrewrlee** [comment]
I was not aware of having either of them. 

I didn't manually install them - this error message first I've heard of the vagrant-login module.  

The only other modules I have manually installed are vagrant-vbguest and vagrant-cachier.

**Comment by sneal** [comment]
If anything this is a core Vagrant issue. I've seen several issues similar to this about Vagrant downgrading already installed plugins when installing another plugin. Bundler, which Vagrant uses internally does so to resolve compatible versions.
