### ISSUE TITLE
Error Configuring and enabling network interfaces

### ISSUE THREAD

**Issue by dhawal55** [WinRb/vagrant-windows#195]
I'm trying to use vagrant 1.4.3 with vagrant-windows 1.6 and get the below error:

[server] Configuring and enabling network interfaces...
C:/Users/XXX/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/communication/guestnetwork.rb:93:in `Integer': invalid value for Integer(): "" (ArgumentError)
        from C:/Users/XXX/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/communication/guestnetwork.rb:93:in`wsman_version'
        from C:/Users/XXX/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/communication/guestnetwork.rb:29:in `network_adapters'
        from C:/Users/XXX/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/guest/cap/configure_networks.rb:55:in`create_vm_interface_map'
        from C:/Users/XXX/.vagrant.d/gems/gems/vagrant-windows-1.6.0/lib/vagrant-windows/guest/cap/configure_networks.rb:24:in `configure_networks'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/guest.rb:88:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/guest.rb:88:in `capability'

**Comment by ccariou** [comment]
@dhawal55 , did you find a workaround to this bug ?

**Comment by sneal** [comment]
This plugin is no longer maintained since Vagrant natively supports Windows guests. If you have a Vagrant issue you need to ask the Vagrant mailing list or file a GitHub issue on [Vagrant core](https://github.com/mitchellh/vagrant).
