### ISSUE TITLE
Upgrade path to 1.6

### ISSUE THREAD

**Issue by dmjio** [WinRb/vagrant-windows#197]
Hi, I'm on vagrant 1.5.1. I see that vagrant 1.6 natively supports windows now. Without breaking my current build environment (too badly) what would be the best way to upgrade to 1.6 and retain my current windows VM that I have working well with vagrant 1.5.1 and vagrant-windows?

BTW thanks for making this plugin, life-saver

**Comment by juliandunn** [comment]
I didn't have any problems upgrading from 1.5.x to 1.6 and continuing to use my existing Windows vagrant boxes. You just need to follow the generic instructions for (possibly) reinstalling plugins into the new Vagrant, minus, of course, vagrant-windows.

**Comment by sneal** [comment]
Besides what @juliandunn said, the biggest change is to your Vagrant files.

remove 

``` ruby
  config.vm.guest = :windows
  config.vm.network :forwarded_port, guest: 5985, host: 5985, auto_correct: true
```

and add

``` ruby
config.vm.communicator = :winrm
```

Unfortunately if you have a bunch of builds setup to use vagrant-windows on Vagrant pre 1.6 like I do, you'll have to do it all at once or partition your builds to specific build servers.
