### ISSUE TITLE
Command alias for 'mkdir' is broken (typo)

### ISSUE THREAD

**Issue by simon-wenmouth** [WinRb/vagrant-windows#23]
In the file

[command_alias.ps1](https://github.com/BIAINC/vagrant-windows/blob/master/lib/vagrant-windows/scripts/command_alias.ps1#L14)

The line

``` powershell
New-Item $p -Type Directory -Force | Out-Null
```

is meant to be

``` powershell
New-Item $path -Type Directory -Force | Out-Null
```

**Comment by davidpellerin** [comment]
I've submitted a pull request for this. 

https://github.com/BIAINC/vagrant-windows/pull/24

**Comment by pmorton** [comment]
This has been merged
