### ISSUE TITLE
Action 'change_host_name" issued under powershell (not cmd)

### ISSUE THREAD

**Issue by simon-wenmouth** [WinRb/vagrant-windows#25]
The change_host_name method on line 15 in file

[lib/vagrant-windows/guest/windows.rb](https://github.com/BIAINC/vagrant-windows/blob/master/lib/vagrant-windows/guest/windows.rb)

calls `channel.execute` without options and is therefore run under powershell. The default of powershell is specified on line 65 in file

[lib/vagrant-windows/communication/winrm.rb](https://github.com/BIAINC/vagrant-windows/blob/master/lib/vagrant-windows/communication/winrm.rb)

As such, I think the line

``` ruby
vm.channel.execute("wmic computersystem where name=\"%COMPUTERNAME%\" call rename name=\"#{name}\"")
```

should actually be

``` ruby
vm.channel.execute("wmic computersystem where name=\"%COMPUTERNAME%\" call rename name=\"#{name}\"", :shell => :cmd)
```

Run under powershell the statement fails with "Description: Invalid Query".

I believe this to be the root cause of these defects in other projects
- https://github.com/hh/windows-fromscratch/issues/4
- https://github.com/WinRb/WinRM/issues/33

The script

``` bash

#!/usr/bin/env ruby

require 'winrm'

endpoint='http://127.0.0.1:5985/wsman'

winrm = WinRM::WinRMWebService.new(endpoint, :plaintext,
   :user=>'vagrant',
   :pass=>'vagrant',
   :basic_auth_only=>true,
   :disable_sspi=>true
)

output = winrm.cmd('wmic computersystem where name="%COMPUTERNAME%" call rename name="W12-RES-DC01X"') do | stdout, stderr |
    STDOUT.print stdout
    STDERR.print stderr
end 
STDOUT.print output.to_yaml

output = winrm.powershell('wmic computersystem where name="%COMPUTERNAME%" call rename name="W12-RES-DC01X"') do | stdout, stderr |
    STDOUT.print stdout
    STDERR.print stderr
end
STDOUT.print output.to_yaml
```

demonstrates that the command issued by change_host_name works under CMD

```
Executing (\\W12-RES-DC01X\ROOT\CIMV2:Win32_ComputerSystem.Name="W12-RES-DC01X")->rename()
Method execution successful.

Out Parameters:
instance of __PARAMETERS
{
    ReturnValue = 0;
};
--- 
:data: 
- :stdout: |
    Executing (\\W12-RES-DC01X\ROOT\CIMV2:Win32_ComputerSystem.Name="W12-RES-DC01X")->rename()

- :stdout: |
    Method execution successful.

- :stderr: "\r\n"
- :stdout: |
    Out Parameters:
    instance of __PARAMETERS
    {
        ReturnValue = 0;
    };

:exitcode: 0
```

but not Powershell

```
Invalid Verb Switch.
--- 
:data: 
- :stderr: |
    Invalid Verb Switch.

:exitcode: 1
```

**Comment by pmorton** [comment]
@simon-wenmouth Can you submit a pull request for this?

**Comment by sneal** [comment]
Fixed in vagrant 1.1 branch.

**Comment by sneal** [comment]
@simon-wenmouth Try this in the 1.0 gem, should be fixed.

**Comment by pmorton** [comment]
Going to mark this as closed. @simon-wenmouth please ping me if this is not the case.
