### ISSUE TITLE
vagrant provision failes on windows

### ISSUE THREAD

**Issue by wenns** [WinRb/vagrant-windows#26]
The vagrant provision command failes for me with:

"Shared folders that Puppet requires are missing on the virtual machine.
This is usually due to configuration changing after already booting the
machine. The fix is to run a `vagrant reload` so that the proper shared
folders will prepared and mounted on the VM."

Running with debug logging enabled reveals that vagrant is checking existence of a unix path "/tmp/vagrant-puppet/manifests":

DEBUG winrm: 1
DEBUG winrm: if(-not (test-path /tmp/vagrant-puppet/manifests)) {exit 1}  EXIT STATUS 1
ERROR warden: Error occurred: Shared folders that Puppet requires are missing on the virtual machine.

Im running:
Host: Linux
Guest: Windows 7
Provisioner: Puppet

**Comment by pmorton** [comment]
So this is a bit tricky. /tmp/vagrant/puppet/manifests will resolve to C:\temp\vagrant\manifests. (Strange I know). If you have added a new provisioner to your code, this is expected. That being said, have you added a new provisioner to your code? If so a reload is required.

**Comment by wenns** [comment]
On 04/26/2013 02:31 AM, Paul Morton wrote:

> So this is a bit tricky. /tmp/vagrant/puppet/manifests will resolve to
> C:\temp\vagrant\manifests. (Strange I know). If you have added a new
> provisioner to your code, this is expected. That being said, have you
> added a new provisioner to your code?
> 
> If so a reload is required.

Thats what vagrant suggests in the error message and I did it already (a 
couple of times, actually). No, my problem cannot be resolved by this.

The strange thing is that the path 'C:\temp\vagrant\manifests' doesnt 
even exist on my machine. So vagrant is right when it complains. Looking 
at things I noticed a script which is responsible for providing this path:
lib/vagrant-windows/scripts/mount_volume.ps1.erb
My impression is that it isnt called for some reason.

**Comment by sneal** [comment]
While porting this plugin to Vagrant 1.1 I ran into the same issue. The chef and puppet provisioners in core Vagrant synchronize folders to the VM. For some reason the puppet provisioner doesn't specify an "id" in the sync options while the chef provisioner does. Without the id specified the mapping fails because it tries to use an invalid sharename of "/tmp/puppet/manifests" rather than just "manifests".

The vagrant-windows 1.1 branch works around this by using a hardcoded sharename of v-manifests-1 in the puppet provisioner monkey patch. I'm not yet sure if the root problem is core vagrant or not.

**Comment by pmorton** [comment]
@wenns The 1.0 version was released today. This provides compat with vagrant 1.1 and is seems that @sneal has addressed this issue in the lastest release. Are you able to confirm that this is the case?

**Comment by wenns** [comment]
I'll check

**Comment by pmorton** [comment]
@sneal  do you feel comfortable closing this?

**Comment by sneal** [comment]
@pmorton I ran into the same exact issue when I first tried getting the Puppet provisioner working. This is definitely fixed.
