### ISSUE TITLE
Windows Vagrant 1.1.4 and Vagrant-Windows 0.2.0 Not Working

### ISSUE THREAD

**Issue by ifunky** [WinRb/vagrant-windows#28]
Hi,

I've got vagrant/vagrant windows working on one of my machines but running an old version of vagrant (0.7.0) so I'm trying to update everything so I can use 1.1+ but I'm having difficulties getting it going.

Here's what I've done:
- installed Vagrant 1.1.4 (also tried 1.1.5)
- Downloaded latest branch and followed rake build instructions to build vagrant-windows 0.2.0.gem
- Ran vagrant plugin install pkg\vagrant-windows-0.2.0.gem which succeeded

When I run vagrant -v I receive:

PS C:\vagrant\Win2008> vagrant -v
 INFO global: Vagrant version: 1.1.4
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: RedHat guest
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: Fedora host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: OpenSUSE host
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: shell
 INFO vagrant: `vagrant` invoked: ["-v"]
 INFO environment: Environment initialized (#Vagrant::Environment:0x2b005c0)
 INFO environment:   - cwd: C:/vagrant/Win2008
 INFO environment: Home path: C:/Users/gibbonsd/.vagrant.d
 INFO environment: Local data path: C:/vagrant/Win2008/.vagrant
 INFO environment: Loading plugin from JSON: vagrant-windows
ERROR root: Failed to load plugin: vagrant-windows
ERROR root:  -- Error: #<LoadError: cannot load such file -- vagrant-windows>
ERROR root:  -- Backtrace:
ERROR root: C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/vagrant/vagrant/embedded/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.4/lib/vagrant.rb:186:in `require_plugin'
C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.4/lib/vagrant/environment.rb:647:in`block in load_plugins'
C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.4/lib/vagrant/environment.rb:644:in `each'
C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.4/lib/vagrant/environment.rb:644:in`load_plugins'
C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.4/lib/vagrant/environment.rb:128:in `initialize'
C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.4/bin/vagrant:53:in`new'
C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.4/bin/vagrant:53:in `<top (required)>'
C:/vagrant/vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in`load'
C:/vagrant/vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `<main>'
 INFO interface: error: The plugin "vagrant-windows" could not be found. Please make sure that it is
properly installed via`vagrant plugin`. Note that plugins made for
Vagrant 1.0.x are not compatible with 1.1+ and this error will likely
continue to show when you use`plugin install` with a 1.0.x plugin.

The plugin "vagrant-windows" could not be found. Please make sure that it is
properly installed via `vagrant plugin`. Note that plugins made for
Vagrant 1.0.x are not compatible with 1.1+ and this error will likely
continue to show when you use `plugin install` with a 1.0.x plugin.
 INFO environment: Running hook: environment_load
 INFO environment: Initializing config...
 INFO loader: Set :default = "C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.1.4/config/default.rb"
 INFO loader: Set :root = #Pathname:C:/vagrant/Win2008/Vagrantfile
 INFO loader: Loading configuration in order: [:default, :home, :root]
 INFO hosts: Host class: VagrantPlugins::HostWindows::Host
 INFO runner: Running action: #Vagrant::Action::Builder:0x1f9d268
 INFO cli: CLI: ["-v"] nil []
 INFO interface: info: Vagrant version 1.1.4
Vagrant version 1.1.4
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: #Vagrant::Action::Builder:0x3177db0

I'd really like to get this going and it looks close but I'm stuck now.  Any ideas?

Thanks

Dan

**Comment by ifunky** [comment]
Oh forgot to add I'm running this on Windows 7!

**Comment by davidpellerin** [comment]
@ifunky what does "vagrant plugin list" display?

**Comment by ifunky** [comment]
Hello,

That command gives me:

 INFO global: Vagrant version: 1.1.4
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: RedHat guest
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: Fedora host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: OpenSUSE host
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: shell
 INFO vagrant: `vagrant` invoked: ["plugin", "list"]
 INFO environment: Environment initialized (#<Vagrant::Environment:0x2b36
 INFO environment:   - cwd: C:/vagrant/Win2008
 INFO environment: Home path: C:/Users/gibbonsd/.vagrant.d
 INFO environment: Local data path: C:/vagrant/Win2008/.vagrant
 INFO environment: Loading plugin from JSON: vagrant-windows
 WARN root: VAGRANT_NO_PLUGINS is set, not loading 3rd party plugin: vagr
 INFO environment: Running hook: environment_load
 INFO environment: Initializing config...
 INFO loader: Set :default = "C:/vagrant/vagrant/embedded/gems/gems/vagra
 INFO loader: Set :root = #<Pathname:C:/vagrant/Win2008/Vagrantfile>
 INFO loader: Loading configuration in order: [:default, :home, :root]
 INFO hosts: Host class: VagrantPlugins::HostWindows::Host
 INFO runner: Running action: #Vagrant::Action::Builder:0x5f9ca0
 INFO cli: CLI: [] "plugin" ["list"]
 INFO runner: Running action: #Vagrant::Action::Builder:0x2a63e58
 INFO warden: Calling action: #<VagrantPlugins::CommandPlugin::Action::Bu
 INFO warden: Calling action: #<VagrantPlugins::CommandPlugin::Action::Li
 INFO interface: info: vagrant-windows (0.2.0)
vagrant-windows (0.2.0)
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: #<Vagrant::Action::Builder:0x2ac1b90>

Thanks

Dan

**Comment by sneal** [comment]
Try the 1.0 gem that we published earlier today. You'll need to uninstall 0.2.0 first: vagrant plugin uninstall vagrant-windows. Then you can run: vagrant plugin install vagrant-windows

**Comment by ifunky** [comment]
Excellent that was good timing!  Everything works now using vagrant 1.1.5 and virtualbox 4.2.12.

I seem to have to manually do gem install winrm afterwards, should this be automatic as it's a dependency?

Thanks!

Dan

**Comment by sneal** [comment]
@ifunky Just curious, with 0.2.0 were you building from a GitHub tarball or zip?

You shouldn't need to install winrm afterwards, but I've never explicitly tried removing it from my machine and installing the plugin to see if vagrant pulls it in automatically or not.

**Comment by ifunky** [comment]
Thanks for the info I'll try and install on a blank pc and see what it does,  I'm writing up a blog post on automating this for Windows.

I built 0.2.0 straight from the zip.

**Comment by sneal** [comment]
Building the gem directly from the zip/tar doesn't work. We use git to gather the list of files to include in the gem. Should probably change that so its independent of git.

**Comment by pmorton** [comment]
@ifunky I am going to go ahead and close this issue. I am confident that @sneal s comment reflects that source of the problem. In better news, we have released 1.0.x which is compatible with vagrant 1.1. Please give it a shot and ping me back if it continues to not work.
