### ISSUE TITLE
Synced Folder is Read-Only

### ISSUE THREAD

**Issue by bassrock** [WinRb/vagrant-windows#31]
For some reason using vagrant-windows 1.0.0 and vagrant 1.1.4, the synced folder is Read-only where I can only create folders. However if I use the absolute path at \vboxsrv\vagrant-root\vagrant, I can write new files.

Is this expected behavior or am I missing something in the setup?

**Comment by bassrock** [comment]
It looks like this may be a bug with virtual box, as manually created shared folders in virtual box has the same issue.

**Comment by sneal** [comment]
Closing this issue, this works correctly on vagrant 1.2.2 and vagrant-windows 1.2 branch.

config.vm.synced_folder "/Users/sneal/src", "/src"

Creates a synced folder on the guest accessible via c:\src, I can read and write to this folder from the guest.
