### ISSUE TITLE
Shell provisioner for windows does not work

### ISSUE THREAD

**Issue by patux** [WinRb/vagrant-windows#38]
When I try to use a script.ps1 to do shell provisioner this does not work and vagrant send this as output:
# < CLIXML

<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">The token '&amp;&amp;' is not a valid statement separator in this version._x000D__x000A_</S><S S="Error">At line:34 char:31_x000D__x000A_</S><S S="Error">\+ chmod +x /tmp/vagrant-shell &amp;&amp; &lt;&lt;&lt;&lt;  /tmp/vagrant-shell_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ParserError: (&amp;&amp;:String) [], ParentContainsError _x000D__x000A_</S><S S="Error">   RecordException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : InvalidEndOfLine_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>

**Comment by sneal** [comment]
Fixed in 1.0.3
