### ISSUE TITLE
Chef Porovisioner fails on first attempt

### ISSUE THREAD

**Issue by Keno** [WinRb/vagrant-windows#4]
I'm using vagrant-windows to manage a windows 7 guest that I'd like to provision with chef. However, every time I create a new VM using `vagrant up`, chef fails with the message that it can't find any cookbook. I have tried to debug the problem but just retrying `vagrant provision` makes it go away (interestingly `vagrant up --no-provision` and then `vagrant provision` works half of the time, but also fails half the time). Any ideas?

**Comment by dpetzel** [comment]
I had a similar problem, that I worked around by hacking the provision file in vagrant itself, I'm not sure where the "proper" fix belongs so I don't have any open pull request, but see if https://github.com/dpetzel/vagrant/commit/3b2f6251724beff352bb2d99901aa25431380aec lets you work around the issue.

**Comment by pmorton** [comment]
Would it make sense to have the mapping provisioner wait some time. i.e.

``` powerhsell
$tries = 6
while (-not Test-Path "$MountPoint" -and $tries -le 6)
{
  sleep 10
}
```

@dpetzel I am not sure that I understand what the hack is doing. It looks like it is just running a net use without error checking. Any idea how running the net use solves the problem? Do you think that running this in the mount script would solve you specific issue?

**Comment by dpetzel** [comment]
Yes all it does it a net use with no error checking. I can't explain WHY it works, but it has solved the issue for me.

As far as the wait time, in the testing that I did, I would tried waiting upwards of 30 minutes and it still would not work. They only success I had was manually running the net use, and then the provisioner would work fine. 

Running the net use in the mount script might just work, but since I don't really know the root cause of the issue, its hard to say for sure.

**Comment by Keno** [comment]
@pmorton Putting it in the mount script does work (though the actual `net use` command fails). See https://github.com/julia-ci/vagrant-windows/blob/master/lib/vagrant-windows/scripts/mount_volume.ps1.erb

**Comment by pmorton** [comment]
Perfect that is what I was going to ask. So  I will test things out with 

```
& net use $share
```

**Comment by pmorton** [comment]
Published a new version to ruby gems to fix this issue. 0.1.0

**Comment by daspilker** [comment]
Everything is working, but the net use command causes an error message on my Windows Server 2008 R2 box. Is that normal?

```
[default] Mounting shared folders...
[default] -- v-root: /vagrant
←[36mwinrm←[0m System error 67 has occurred.
←[36mwinrm←[0m
←[36mwinrm←[0m The network name cannot be found.
←[36mwinrm←[0m
←[36mwinrm←[0m Attempting to mount v-root to C:\vagrant
←[36mwinrm←[0m symbolic link created for C:\vagrant <<===>> \\vboxsrv\v-root
```
