### ISSUE TITLE
Error while using vagrant 1.1 

### ISSUE THREAD

**Issue by kamalim** [WinRb/vagrant-windows#42]
Hi:
I have recently updated to vagrant 1.1
I am getting below error while trying to do vagrant up

[win1] Waiting for VM to boot. This can take a few minutes.
[win1] Failed to connect to VM!
Failed to connect to VM via SSH. Please verify the VM successfully booted
by looking at the VirtualBox GUI.

My vagrant, vagrant-windows, winrm versions are as below:
kamalim:selenium_grid kamalim$ vagrant -v
Vagrant version 1.1.5
kamalim:selenium_grid kamalim$ gem list vagrant-windows

**\* LOCAL GEMS ***

vagrant-windows (1.0.1)
kamalim:selenium_grid kamalim$ gem list winrm

**\* LOCAL GEMS ***

winrm (1.1.2)

My vagrant file snippet is as :+1: 
Vagrant::Config.run do |config|
config.vm.define :win1 do |win1_config|
        win1_config.vm.guest = :windows
        win1_config.vm.box = "win7_enVL"
        win1_config.vm.boot_mode = :gui
        win1_config.vm :forward_port, guest: 3389, host: 3390
        win1_config.vm :forward_port, guest: 5985, host: 5985
        win1_config.vm.network :hostonly, "192.168.200.12"

Please help

**Comment by sneal** [comment]
Did you upgrade your Vagrantfile syntax to version 2? See the [readme for an example](https://github.com/WinRb/vagrant-windows#the-vagrant-file).

**Comment by kamalim** [comment]
Yes I did that.

Looks like it created the VM , but tries to do ssh in it and failes.

Here is how my Vagrantfile looks like:

Vagrant.configure("2") do |config|

config.vm.define :win1 do |win1_config|
        win1_config.vm.guest = :windows
        win1_config.vm.box = "win7_enVL"

```
    win1_config.vm.network :forwarded_port, guest: 3389, host: 3389
    win1_config.vm.network :forwarded_port, guest: 5985, host: 5985
    win1_config.vm.network :private_network, ip:  "192.168.200.12"

    win1_config.vm.provider "virtualbox" do |v|
      v.gui = true
      v.name = "win-7"
    win1_config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "cookbooks"
     chef.add_recipe("chef_handler")
     chef.add_recipe("windows")
     chef.add_recipe("firefox")
     chef.add_recipe("java")
     chef.add_recipe("chrome")
     chef.add_recipe("iexplorer")
     chef.add_recipe("selenium::client")
```

   end

  end

end

**Comment by mgriffin** [comment]
In the readme (just above "What Works?"), it says that config.windows and config.winrm have to be defined. If you add something like

``` ruby
config.windows.halt_timeout = 15
config.winrm.username = "vagrant"
config.winrm.password = "vagrant"
```

to your Vagrantfile, it should pick up that it's running vagrant-windows. Try that and see if it works.

**Comment by kamalim** [comment]
Hi,

I did that and after that it started using winrm , but gives this error:

An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction SilentlyContinue)
    if($null -eq $command)
    {
      exit 1
    }
    write-host $command[0].Definition
    exit 0
}

function test ([Switch] $d, [String] $path) {
  if(Test-Path $path)
  {
    exit 0
  }
  exit 1
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $path -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected

**Comment by mgriffin** [comment]
That's the same error I'm getting in issue #43

**Comment by kamalim** [comment]
Hi,

I have solved the issue by increasing the config.winrm.max_tries -The number of retries to connect to WinRM. It defaults to 12.I increased it to 20.
Here is what my vagrant file looks like:

Vagrant.configure("2") do |config|

  config.vm.define :win1 do |win1_config|

```
    win1_config.vm.box = "win7_enVL"
    win1_config.vm.guest = :windows

    win1_config.windows.halt_timeout = 15
    win1_config.winrm.max_tries = 20

    win1_config.vm.network :forwarded_port, guest: 3389, host: 3389
    win1_config.vm.network :forwarded_port, guest: 5985, host: 5985
```

**Comment by kamalim** [comment]
The reason behind the error "HTTPClient::KeepAliveDisconnected" is : 
WinRM uses http to connect to the guest.Once the windows got installed on box  it restarted for installing the recent updates.When retrying a failed persistent connection, httpclient should use a fresh connection.
More details can be found here :   https://github.com/nahi/httpclient/issues/30

So I increased the maximum winrm retries and it continued further.

**Comment by sneal** [comment]
I'm glad you were able to figure this out.
