### ISSUE TITLE
An error occurred executing a remote WinRM command

### ISSUE THREAD

**Issue by mgriffin** [WinRb/vagrant-windows#43]
Hi.

I'm having problems getting a Windows 2008R2 server running on a Windows 7 host. I have set up my own server base box and enabled winrm. I've stopped the firewall as well to make sure that that's not causing the problem.

I used the basic Vagrantfile from the readme but when I run vagrant up, I get an error saying that "An error occurred executing a remote WinRM command". Then it shows the powershell command.

The server comes up okay, I can see it after setting the gui to be on and the command runs fine from the command line so winrm is working.

I've tried this with vagrant 1.1 and 1.2 and vagrant-windows 1.0.1, 1.0.2, 1.1.0

**Comment by sneal** [comment]
I have a Win7 host running a Win2k8 guest, so that configuration can work. It sounds like its connecting OK to your guest, but failing to run a command on the guest. Can you run vagrant in debug mode and send a gist of the output?

**Comment by mgriffin** [comment]
https://gist.github.com/mgriffin/5618534

That's most of the output from the debug. If you want to have a look at the very beginning of it as well, I can add that in. Thanks for looking at it.

Here's the Vagrantfile that I used

``` ruby
require 'vagrant-windows'

Vagrant.configure("2") do |config|

  # Max time to wait for the guest to shutdown
  config.windows.halt_timeout = 15

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--natnet1", "192.168/16"]
  end

  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  # Configure base box parameters
  config.vm.box = "win2k8r2-new"
  config.vm.guest = :windows

  # Port forward WinRM and RDP
  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985

end
```

**Comment by sneal** [comment]
Does increasing the retry count solve your problem? I can see in your debug output that it keeps testing to see if the host is up, but eventually gives up.

**Comment by mgriffin** [comment]
Yeah, after upping the retry count it worked perfectly. I set it to 20 and that did the job. 

For anyone looking at this in the future add this to the Vagrantfile

``` ruby
config.winrm.max_tries = 20
```

**Comment by DracoBlue** [comment]
I had the same issue. Updating to 1.5.0 of vagrant-windows, fixed the issue.
