### ISSUE TITLE
The specified guest type is unknown: windows.

### ISSUE THREAD

**Issue by collinanderson** [WinRb/vagrant-windows#50]
Hello,

I'm trying to get vagrant-windows working on ubuntu 12.10 and running into this error:

$ vagrant up
The specified guest type is unknown: windows. Please change this
to a proper value.

Any idea where I've gone wrong? See my setup below.

Thanks,
Collin

sudo aptitude update
sudo aptitude install linux-headers-$(uname -r)
sudo aptitude install virtualbox
sudo aptitude install rubygems ruby-dev libxml2-dev libxslt-dev
gem install -r vagrant-windows -v 0.1.2
vagrant box add win2k8r2 http://dl.dropbox.com/u/58604/vagrant/win2k8r2-core.box
vagrant init win2k8r2
vagrant up

**Comment by juliandunn** [comment]
@collinanderson Don't you want to "vagrant plugin install" the vagrant-windows plugin?

**Comment by collinanderson** [comment]
yeah, maybe I should use a newer version of vagrant that actually has the "plugin" command. Thanks.
