### ISSUE TITLE
Set up working environment for testing vagrant-windows

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/vagrant-windows#51]
Hi,

I am planning to test vagrant-windows project using various windows versions. 

My current setup looks like this:
1. OS: Mac OSX 10.8.4
2. Vagrant 1.2.2
3. Virtual Box 4.2.12
4. Ruby 2.0.0p195

I did proceed with the installation of the ruby gem but when I try to launch a box it shows me the following message:

`There are errors in the configuration of this machine. Please fix
the following errors and try again:`

`Vagrant:
 Unknown configuration section 'windows'. 
 Unknown configuration section 'winrm'.
`

I followed all the steps for the Vagrantfile configuration but would like to know if i am missing something.

Thanks.

**Comment by sneal** [comment]
The error indicated that vagrant can't find the plugin, i.e. its not installed. Are you trying to run the gem via bundle exec (i.e. from source) or from the published gem?

**Comment by lmayorga1980** [comment]
I am trying to use the published gem.  This is my current setup using ruby 2.0.0p195

$ gem list --local

**\* LOCAL GEMS ***

akami (1.2.0)
bigdecimal (1.2.0)
builder (3.2.2)
bundler (1.3.5)
bundler-unload (1.0.1)
childprocess (0.3.9)
ffi (1.8.1)
gssapi (1.0.3)
gyoku (1.0.0)
highline (1.6.19)
httpclient (2.2.0.2)
httpi (0.9.7)
io-console (0.4.2)
json (1.7.7)
little-plugger (1.1.3)
logging (1.6.2)
minitest (4.3.2)
multi_json (1.7.5)
nokogiri (1.5.9)
nori (1.1.5)
psych (2.0.0)
rack (1.5.2)
rake (10.0.4, 0.9.6)
rdoc (4.0.0)
rubygems-bundler (1.2.0)
rubyntlm (0.1.1)
rubyzip (0.9.9)
rvm (1.11.3.8)
savon (0.9.5)
selenium-webdriver (2.33.0)
test-unit (2.5.5, 2.0.0.0)
uuidtools (2.1.4)
**vagrant-windows (1.0.3)**
wasabi (1.0.0)
websocket (1.0.7)
winrm (1.1.2)

**Comment by sneal** [comment]
vagrant-windows is installed into your system gem repository, but it needs be installed into Vagrant's gem/plugin repository via: 
`vagrant plugin install vagrant-windows`

**Comment by lmayorga1980** [comment]
Hi,

This worked nicely. I think it should be included on the README.md file.

Thank you for your help

**Comment by sneal** [comment]
You're right, odd that's it not there. I'll add that, thanks!
