### ISSUE TITLE
[vagrant1.2 branch] Error running vagrant reload

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/vagrant-windows#52]
### Environment

---
- OS: Mac OSX 10.8.4
- Vagrant 1.2.2
- Virtual Box 4.2.12
- Ruby 2.0.0p195
- Target Windows Version: Windows Core Server 2012 Standard
- Processor : Intel Core i7 - 64 bit
### Details

---

I am getting the following error in a random sequence.

`windows.rb:10:in initialize: wrong number of arguments (0 for 1) (ArgumentError)`

I am using the published gem **vagrant-windows-1.0.3**

```from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/guest.rb:70:in`new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/guest.rb:70:in `block (3 levels) in detect!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/guest.rb:67:in`each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/guest.rb:67:in `block (2 levels) in detect!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/guest.rb:66:in`each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/guest.rb:66:in `block in detect!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/guest.rb:64:in`catch'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/guest.rb:64:in `detect!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/machine.rb:182:in`guest'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/graceful_halt.rb:47:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:43:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in`busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:51:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/machine.rb:147:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/reload/command.rb:29:in`block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:180:in`each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/plugins/commands/reload/command.rb:28:in`execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/cli.rb:46:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/environment.rb:467:in`cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.2/bin/vagrant:84:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in`load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'

```
```

**Comment by sneal** [comment]
You need to use vagrant 1.1.5 and not vagrant 1.2.2. Its in the readme.md ;)

The published vagrant-windows 1.0.3 gem does not support vagrant 1.2.x, it only supports 1.1.x. The vagrant-1.2 development branch of vagrant-windows does support both vagrant 1.1.x and vagrant 1.2.x, (as of yesterday) but is not published.

**Comment by lmayorga1980** [comment]
Yes. I am using the development branch and try to help you guys find bugs and contribute without actually writing code ;)

**Comment by sneal** [comment]
What does `vagrant plugin list` return?

**Comment by lmayorga1980** [comment]
- $ vagrant plugin list
- vagrant-windows (1.0.3)

**Comment by sneal** [comment]
You're using the release gem which isn't compatible with vagrant 1.2. You need to pull the vagrant-1.2 branch source down from GH and use bundler as documented in the readme.

**Comment by lmayorga1980** [comment]
Hi,

I did remove the vagrant-windows plugin from the vagrant installed plugins and also got the code using the bundler. 

i have the following error

```
 LT71707-MAC:vagrant-win-1.2branch lmo0$ bundle exec vagrant up
 You appear to be running Vagrant in a Bundler environment. Because
 Vagrant should be run within installers (outside of Bundler), Vagrant
 will assume that you're developing plugins and will change its behavior
 in certain ways to better assist plugin development.

 Bringing machine 'default' up with 'virtualbox' provider...
 There are errors in the configuration of this machine. Please fix
 the following errors and try again:

 Vagrant:
 Unknown configuration section 'windows'.
 Unknown configuration section 'winrm'.
```

**Comment by sneal** [comment]
Do you have this line at the top of your Vagrantfile?

`Vagrant.require_plugin "vagrant-windows"`

Wouldn't hurt to read this too http://docs.vagrantup.com/v2/plugins/packaging.html

**Comment by lmayorga1980** [comment]
Fixed.

I think i have my environment ready for testing.
