### ISSUE TITLE
Update Requirements for Windows Core Versions

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/vagrant-windows#53]
#### Environment

---
- OS: Mac OSX 10.8.4
- Vagrant 1.2.2
- Virtual Box 4.2.12
- Ruby 2.0.0p195
- Target Windows Version: Windows Core Server 2012 Standard
- Processor : Intel Core i7 - 64 bit
#### Details

---

Hi,

I think Windows Core 2008/2012 Servers do not need to configure the **Shutdown Event Tracker** or the **Server Manager at Login**. The registry entries for these configurations do not exist. 

http://www.computerperformance.co.uk/windows_server/server-2012-shutdown-event-tracker.htm

**Comment by sneal** [comment]
Fixed in vagrant-windows 1.2
