### ISSUE TITLE
[vagrant1.2 branch] Issue running puppet provisioning

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/vagrant-windows#55]
### Environment

---
- OS: Mac OSX 10.8.4
- Vagrant 1.2.2
- Virtual Box 4.2.12
- Ruby 2.0.0p195
- Target Windows Version: **Windows Core Server 2012 Standard**
- Processor : Intel Core i7 - 64 bit
### Details

---

It seems that puppet client cannot be found from vagrant. 

```
$ bundle exec vagrant up 

[default] Running provisioner: VagrantPlugins::Puppet::Provisioner::Puppet...
The `puppet` binary appears to not be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.
```

![screen shot 2013-06-19 at 7 57 59 pm](https://f.cloud.github.com/assets/3172378/678584/57a1e900-d93c-11e2-917d-dea23ccab73a.png)

**Comment by stonith** [comment]
Try running the puppet --version under the vagrant user.

**Comment by lmayorga1980** [comment]
It seems that the environment variable need to be executed with the **vagrant user**. I think now i have a starting box with Puppet Windows Client.  

I guess I could say now that i have a test environment.

Thank you for the quick responses.
