### ISSUE TITLE
[vagrant-1.2.2]  Add Support to VMWare Fusion Provider

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/vagrant-windows#56]
Hi,

I have installed(purchased) the **VMWare Fusion** provider plugin for Vagrant and I already set my first vmware box but it seems that is not able to recognize the **vmware_fusion** provider
#### Environment

---
- OS: Mac OSX 10.8.4
- Vagrant 1.2.2
- VMWare Fusion 5.0.3
- Ruby 2.0.0p0
- Target Windows Version: Windows Server 2008 R2 Standard
- Processor : Intel Core i7 - 64 bit
#### Details

---

`$ bundle exec vagrant up --provider=vmware_fusion`
You appear to be running Vagrant in a Bundler environment. Because
Vagrant should be run within installers (outside of Bundler), Vagrant
will assume that you're developing plugins and will change its behavior
in certain ways to better assist plugin development.

The provider 'vmware_fusion' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.

**Comment by sneal** [comment]
I haven't tried the vmware fusion provider, but my suspicion is that it can't find the fusion plugin when running under bundler. I would try pinging Mitchell to see if he has a suggestion.

**Comment by lmayorga1980** [comment]
Thanks for the heads up.

**Comment by lmayorga1980** [comment]
Do you know if this project will be finally supported by vagrant as a plugin. Or may be Mitchell is doing his own stuff

**Comment by juliandunn** [comment]
Based on some comments I read, it sounds like he wants to do his own thing, but on what timeline, I don't know.

**Comment by joefitzgerald** [comment]
@lmayorga1980 did you end up finding a way to get the vmware_fusion to run when using bundler?

**Comment by lmayorga1980** [comment]
Not yet

**Comment by joefitzgerald** [comment]
@lmayorga1980 Figured it out with help from @mitchellh. See #69.

**Comment by lmayorga1980** [comment]
Now i see it. Thanks.

Probably mitchell has a surprise for us on windows :)

**Comment by sneal** [comment]
I'm going to close this in favor of issue #69 because it has more information attached even though that one essentially dupes this issue. BTW - got [bundle exec working](http://www.codingonstilts.com/2013/07/how-to-bundle-exec-vagrant-up-with.html) with the fusion provider.
