### ISSUE TITLE
How to use vagrant 1.2 with vagrant-windows "vagrant-1.2" branch?

### ISSUE THREAD

**Issue by robertmircea** [WinRb/vagrant-windows#57]
I've installed (using the installer) vagrant 1.2 on a Windows 8 host. I would like to use vagrant with vagrant-windows "vagrant-1.2" branch. 

How can I install on Windows host this specific version of vagrant-windows?

**Comment by sneal** [comment]
There's no published gem for vagrant 1.2. I've been using it locally for the past couple of weeks without any problems with chef-solo.

You'll need to build it `rake` from source, then install it from your local built copy `vagrant plugin install pkg/vagrant-windows-1.1.0.gem`

**Comment by ferventcoder** [comment]
I just put in a pull request that would add instructions on this to those not familiar with how to do it (and vagrant doesn't have very good documentation spelling out how to install from a gem).
