### ISSUE TITLE
Issue when using specific IP Address

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/vagrant-windows#58]
Hi,

I was trying to use the following configuration since already have a puppet master running with Passenger.

 `config.vm.network :private_network, ip: "10.11.12.16"`
#### Environment

---
- OS: Mac OSX 10.8.4
- Virtual Box 4.2.12
- Ruby 2.0.0p0
- Target Windows Version: Windows Server 2008 R2 Standard
- Processor : Intel Core i7 - 64 bit
### Exception Details

---

``` powershell
An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction SilentlyContinue)
    if($null -eq $command)
    {
      exit 1
    }
    write-host $command[0].Definition
    exit 0
}

function test ([Switch] $d, [String] $path) {
  if(Test-Path $path)
  {
    exit 0
  }
  exit 1
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $path -Type Directory -Force | Out-Null
  }
}


hostname
Message: Connection refused - connect(2) (http://localhost:5985)
```

**Comment by sneal** [comment]
If you login to the guest do you get two network adapters? One for the NAT and one for the private network config?

I tried this exact configuration on vagrant 1.2 and the vagrant1.2 branch version of vagrant-windows and couldn't repro.

**Comment by sneal** [comment]
As a potential workaround you could try setting winrm.host to 10.11.12.16 in your Vagrantfile, vagrant-windows 1.2.2 will use that config value if set.
