### ISSUE TITLE
Chef's output is only displayed in console after completion (or after an error)

### ISSUE THREAD

**Issue by dstj** [WinRb/vagrant-windows#59]
Hi, it may be more a question than a bug report, but I thinking it's worth asking since I couldn't find the answer elsewhere...

I'm running vagrant-windows 1.1 with Virtual Box and Chef. My run-list takes a long time (~25 minutes) and I noticed that it stays on `Running chef-solo...` until it either completes or fails. Then everything get "flushed" to the console. With a Linux box, I see the `[INFO]` outputted "live" which helps identify progression. Is there a way to have that with vagrant-windows too?

Thanks.

**Versions:**
Vagrant 1.1.5
Vagrant-windows 1.1 
Virtual Box 4.2.12 
Chef-solo 11.4.4-2

**Comment by sneal** [comment]
Yeah, I don't like this either. Its an artifact of the secondary .NET process it spins up to start chef-solo. The 'chef-schtasks' branch actually doesn't have this problem and immediately displays output as it happens.

**Comment by dstj** [comment]
Good to know, thanks!
