### ISSUE TITLE
vagrant 1.2 logging busted

### ISSUE THREAD

**Issue by Sauraus** [WinRb/vagrant-windows#60]
I believe logging in vagrant-windows 1.2 branch is broken, I've set VAGRANT_LOG to INFO, WARN & ERROR and I only see messages from vagrant, I cannot find anything by vagrant-windows plugin.

**Comment by sneal** [comment]
WOMM. My host is OS X and I'm running the following command:

`VAGRANT_LOG=debug vagrant up`

Are you running it the same way?

**Comment by sneal** [comment]
I noticed a couple of commits weren't pushed, so perhaps try pulling and rebuilding the plugin. I also bumped the plugin version to 1.2.

**Comment by Sauraus** [comment]
I don't see how those commits would affect logging or did I miss something?

I am on Windows 7 in PowerShell so I do:
PS> $Env:VAGRANT_LOG="DEBUG"
PS> vagrant up

And I can see all the vagrant DEBUG output but nothing from the vagrant-windows plugin.

I was also looking at the code and wondering if the log setup code should not be moved from the Plugin class to vagrant-windows.rb?

**Comment by sneal** [comment]
That seems like it should work. You're right the commits I pushed this morning were just a refactor that shouldn't have affected logging.

**Comment by sneal** [comment]
Tried this on the vagrant-1.2 branch using PowerShell on Win7 like you, I can't repro the issue.
