### ISSUE TITLE
Forcing private network mode to give a default gateway ?

### ISSUE THREAD

**Issue by cournape** [WinRb/vagrant-windows#63]
One issue that comes up with private network is that since there is no default gateway, windows 7 decides to set that network into 'work network' mode, which means you can't access the VM at this ip from the host, making it rather useless.

One (the only ?) way to fix this is to set up a dummy gateway manually through the UI, and then everything works fine. Is there a way we can automate this ? I have not found a way to set up the gateway with netsh, unfortunately.

**Comment by sneal** [comment]
Interestingly, this only seems to be a problem on Windows 7 (probably 8 too). Windows Server 2008 R2 doesn't require that you set the network type to "work network" to enable guest access through the private IP from the host.
