### ISSUE TITLE
chef logging not 'real time' anymore

### ISSUE THREAD

**Issue by cournape** [WinRb/vagrant-windows#64]
When using chef-solo provisioner, we get the log only after chef-solo ran, instead of during the run.

That makes the logging much less useful: is there an easy way to fix this ? I am using the vagrant-1.2 branch on top of vagrant 1.2.4 (issue seen on both osx and linux hosts).

**Comment by sneal** [comment]
I don't like waiting for my chef output either. Its fixed in the chef-schtasks branch.

**Comment by sneal** [comment]
Fixed in vagrant-windows 1.2
