### ISSUE TITLE
Vagrant Puppet provisioner errors out with "The token '||' is not a valid statement separator in this version"

### ISSUE THREAD

**Issue by georgievrado** [WinRb/vagrant-windows#73]
Hi,

I am trying to run the puppet_server provisioner for a Windows Server 2008 R2 box. My set up is the following:
Vagrant 1.1.5
vagrant-windows 1.0.3

The vagrant file looks as follows:

  config.vm.define :webnode do |webnode|
    webnode.vm.box = "Win2008R2"
    webnode.vm.guest = :windows
    webnode.vm.network :private_network, ip: "168.192.73.4", :netmask => "255.255.255.0"
    webnode.windows.halt_timeout = 15
    webnode.winrm.username = "vagrant"
    webnode.winrm.password = "vagrant"
    webnode.winrm.max_tries = 20
    webnode.vm.network :forwarded_port, guest: 3389, host: 3389
    webnode.vm.network :forwarded_port, guest: 80, host: 8080
    webnode.vm.network :forwarded_port, guest: 5985, host: 5985
    webnode.vm.network :forwarded_port, guest: 1433, host: 1433

```
webnode.vm.provider "virtualbox" do |v| 
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.gui = true
end

webnode.vm.provision :puppet_server do |agent|
    agent.puppet_server = "puppet"
    agent.options = "--environment dev"
    agent.facter = {
        "custom_role" => "websrv"
    }       
end
```

  end

When it reaches the part for running the provisioner it bombs out. Full error message:
...
Running Puppet agent...
# < CLIXML

<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
<S S="Error">The token '||' is not a valid statement separator in this version._
x000D__x000A_</S><S S="Error">At line:34 char:83_x000D__x000A_</S><S S="Error">+
 puppet agent --certname Win2008R2SQL2008R2 --server puppet --detailed-exitcod_x
000D__x000A_</S><S S="Error">es || &lt;&lt;&lt;&lt;  [ $? -eq 2 ]_x000D__x000A_<
/S><S S="Error">    + CategoryInfo          : ParserError: (||:String) [], Paren
tContainsError _x000D__x000A_</S><S S="Error">   RecordException_x000D__x000A_</
S><S S="Error">    + FullyQualifiedErrorId : InvalidEndOfLine_x000D__x000A_</S><
S S="Error"> _x000D__x000A_</S></Objs>

**Comment by georgievrado** [comment]
The same issues reproduces with Vagrant 1.2 and vagrant-windows plugin built from this branch: https://github.com/WinRb/vagrant-windows/tree/vagrant-1.2.

**Comment by sneal** [comment]
We need to monkey patch the vagrant [puppet server provisioner](http://docs.vagrantup.com/v2/provisioning/puppet_agent.html). Right now it looks like we only support the [puppet apply provisioner](http://docs.vagrantup.com/v2/provisioning/puppet_apply.html).

**Comment by georgievrado** [comment]
@sneal  thanks. I will be calling the puppet agent from a PowerShell script. Note that seems that injecting Facter facts during runtime as described here: http://www.puppetcookbook.com/posts/override-a-facter-fact.html and used by the provisioner https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/puppet/provisioner/puppet_server.rb#L62 does not seem to work on Windows Puppet Agent.

**Comment by ferventcoder** [comment]
This should be done like this:

```
SET FACTER_operatingsystem=Debian
facter operatingsystem
```

But this probably belongs to another issue.

**Comment by ferventcoder** [comment]
FWIW, when I provide overridden facts it works fine with the agent. I'm using 1.2.7 of Vagrant, 1.2.0 gem (with jbronn's patch):

``` ruby
  config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = "puppet/modules"
    puppet.facter = {
      "domain" => "local",
      "kernel" => "windows",
      "operatingsystem" => "windows",
      "osfamily" => "windows",
    }
  end
```

**Comment by georgievrado** [comment]
Yep, the puppet agent provisioner works fine with this gem. The problem persists when you try to use the puppet server provisioner.

**Comment by sneal** [comment]
I don't have a puppet server, so I'm not going to be able to fix this. PR would be welcomed.
