### ISSUE TITLE
[vagrant-1.2 branch] Puppet provisioning error?

### ISSUE THREAD

**Issue by gpurkins** [WinRb/vagrant-windows#76]
I'm using puppet with vagrant-windows on the 1.2 branch, and it seems like it wants to error with the following:

[default] Mounting shared folders...
[default] -- /vagrant
[default] -- /tmp/vagrant-puppet/manifests
[default] Running provisioner: puppet...
The remote command returned a bad exit status of 1.

Shell: powershell
Command: chmod 0777 /tmp/vagrant-puppet

My current work around is to fire puppet via shell provider.

**Comment by sneal** [comment]
Do you know if this error is new in the vagrant-1.2 branch of vagrant-windows?

**Comment by ferventcoder** [comment]
Can you run this with

```
SET VAGRANT_LOG=DEBUG
Vagrant provision
```

**Comment by ferventcoder** [comment]
Puppet provisioner works in the released gem.

**Comment by gpurkins** [comment]
My group has just moved to vagrant 1.2.x so we have support for vagrant-aws. The released gem, from docs and trying it ,does not work for 1.2, I grabbed the 1.2-branch and built it. I had noticed there was a previous issue with chmodding in issues, wonder if jts related. When I get to my terminal, I'll run with debug on. 

There is a workaround using shell provisioner. :shell, :inline => "puppet apply C:\vagrant\puppet.pp", provided you leave the puppet recipe in the dir you are upping from.

**Comment by amtrack** [comment]
Another workaround is to specify the `temp_dir` for the puppet config (see https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/puppet/config/puppet.rb)

```
config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "main.pp"
    puppet.module_path = "puppet/modules"
    puppet.temp_dir = "C:/tmp/vagrant-puppet"
end
```

**Comment by gpurkins** [comment]
It looks like WinRM fires off fine, but then it tries chmod, which is no bueno in PowerShell:

which puppet
DEBUG winrmcommunicator: Exit status: 0
DEBUG winrmcommunicator: powershell executing:
function which {
    $command = [Array](Get-Command $args[0] -errorAction SilentlyContinue)
    if($null -eq $command)
    {
      exit 1
    }
    write-host $command[0].Definition
    exit 0
}

function test ([Switch] $d, [String] $path) {
  if(Test-Path $path)
  {
    exit 0
  }
  exit 1
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $path -Type Directory -Force | Out-Null
  }
}

mkdir -p /tmp/vagrant-puppet
DEBUG winrmcommunicator: Exit status: 0
DEBUG winrmcommunicator: powershell executing:
function which {
    $command = [Array](Get-Command $args[0] -errorAction SilentlyContinue)
    if($null -eq $command)
    {
      exit 1
    }
    write-host $command[0].Definition
    exit 0
}

function test ([Switch] $d, [String] $path) {
  if(Test-Path $path)
  {
    exit 0
  }
  exit 1
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $path -Type Directory -Force | Out-Null
  }
}

chmod 0777 /tmp/vagrant-puppet
DEBUG winrmcommunicator: Exit status: 1
ERROR warden: Error occurred: The remote command returned a bad exit status of 1.

Shell: powershell
Command: chmod 0777 /tmp/vagrant-puppet
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The remote command returned a bad exit status of 1.

Shell: powershell
Command: chmod 0777 /tmp/vagrant-puppet
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x000000029fe5c8
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The remote command returned a bad exit status of 1.

Shell: powershell
Command: chmod 0777 /tmp/vagrant-puppet
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x0000000207c9f0
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The remote command returned a bad exit status of 1.

**Comment by ferventcoder** [comment]
There was a pull request on this #82

**Comment by sneal** [comment]
I believe this is resolved, if not please reopen.
