### ISSUE TITLE
Errors in chef run during chef provisioning aren't causing the vagrant provision to stop with an error

### ISSUE THREAD

**Issue by kashook** [WinRb/vagrant-windows#80]
I've been testing the latest code on the vagrant-1.2 branch.  I have several VMs that have multiple chef provisioners.  I've noticed that if one of the chef runs fails, it seems to move on and run the next provisioner instead of stopping the vagrant provision with an error.  I haven't investigated in depth, but my first guess is that the powershell script that's being run to do the chef run in monkey_patches\chef_solo.rb is failing to returning a non-zero exit code when it should be.

**Comment by sneal** [comment]
Thanks for reporting this, I'll take a look at this in about a week.

**Comment by sneal** [comment]
Fixed
