### ISSUE TITLE
Chef client provisioner output is garbled when using the vagrant-1.2 branch of vagrant-windows with Vagrant 1.2.5+

### ISSUE THREAD

**Issue by kashook** [WinRb/vagrant-windows#83]
Vagrant has two chef provisioners: chef_solo and chef_client.  I noticed recently when using the chef_client provisioner with a windows guest that the chef output is garbled in the console.  Each line of the log appears to overwrite the previous line as new lines are printed.  I've tracked this down to a combination of two things.  First, Vagrant made a change to all of their provisioners that change how new lines are handled.  (See the changeset [here](https://github.com/mitchellh/vagrant/commit/8379d0e20e72f5dfdb766bca496e464b0791f896)).  Second, in winrmcommunicator.rb in vagrant-windows, the handle_out method splits the log output line by line and calls a block for each line to actually print the output instead of giving the entire output to the block.  Since vagrant stopped including new lines in the blocks in the changeset linked above, the log output is now messed up.

This issue currently doesn't show up in chef solo provisioners because chef_solo.rb was copied and monkey patched from an older version of vagrant where new line characters are still being inserted, so we sort of luck out that the monkey patched code is "out of date".  However, there is no monkey patch for chef_client.rb, so Vagrant's original version is being used as-is.

**Comment by kashook** [comment]
Pull request: https://github.com/WinRb/vagrant-windows/pull/84

**Comment by pmorton** [comment]
Resolved by #84
