### ISSUE TITLE
vagrant winrm command -- add support like vagrant ssh

### ISSUE THREAD

**Issue by Iristyle** [WinRb/vagrant-windows#86]
Since the code is already written to do WinRM communication, it seems like a next logical step would be to implement a `vagrant winrm` command that acted as a REPL against the remote host.

The [Vagrant command docs](http://docs.vagrantup.com/v2/plugins/commands.html) seem pretty straight forward.

Have you given this any thought, or are there major sticking points to making this work properly?

**Comment by sneal** [comment]
This is definitely something I'd like to see implemented. I'd like to wait until we upgrade to winrm2 gem since it has much better support builtin for this type of scenario.

**Comment by ferventcoder** [comment]
Yeah, :+1:

**Comment by benjamine** [comment]
This would be very helpful.
In the meantime, in case anyone finds it useful, I wrote this little ruby script to run a simple command on the windows guest using the winrm gem https://gist.github.com/benjamine/8381365

**Comment by dlai0001** [comment]
:+1:

**Comment by sneal** [comment]
This plugin is no longer maintained since Vagrant natively supports Windows guests. If you have a Vagrant issue you need to ask the Vagrant mailing list or file a GitHub issue on [Vagrant core](https://github.com/mitchellh/vagrant).
