### ISSUE TITLE
Callback to Mac host fails, warning  "Unknown configuration section 'winrm'." at vagrant up 

### ISSUE THREAD

**Issue by etxnija** [WinRb/vagrant-windows#87]
Windows guest 2008 does not notify back after vagrant up so it looks like vagrant is hung. In VirtualBox I can see the box being up. And I get his warning. But as far as I can see everything is installed correctly. 

`

> vagrant up
> There were warnings and/or errors while loading your Vagrantfile.
> Your Vagrantfile was written for an earlier version of Vagrant,
> and while Vagrant does the best it can to remain backwards
> compatible, there are some cases where things have changed
> significantly enough to warrant a message. These messages are
> shown below.
> Warnings:
> - Unknown configuration section "winrm". If this section was part of
>   a Vagrant 1.0.x plugin, note that 1.0.x plugins are incompatible with 1.1+.
>   `

My enviroment:
OS X 10.8.4
Ruby managed by rbenv `ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin12.4.0]`
Vagrant:  `vagrant -v
Vagrant version 1.2.7`
Vagrant Plugins
`vagrant plugin list
vagrant-berkshelf (1.3.3)
vagrant-windows (1.2.0)`

Gems:
`gem list
*** LOCAL GEMS ***
activesupport (4.0.0, 3.2.14)
addressable (2.3.5)
akami (1.2.0)
archive-tar-minitar (0.5.2)
atlassian-stash (0.1.6)
atomic (1.1.13)
berkshelf (2.0.9, 2.0.8)
bigdecimal (1.2.1, 1.1.0)
binding_of_caller (0.7.2)
buff-config (0.3.0)
buff-extensions (0.5.0)
buff-ignore (1.1.0)
buff-ruby_engine (0.1.0)
buff-shell_out (0.1.0)
builder (3.2.2)
bundle (0.0.1)
bundler (1.3.5)
celluloid (0.14.1)
celluloid-io (0.14.1)
chef (11.6.0)
chefspec (1.3.1)
childprocess (0.3.9)
chozo (0.6.1)
ci_reporter (1.9.0)
coderay (1.0.9)
commander (4.1.5)
debug_inspector (0.0.2)
diff-lcs (1.2.4, 1.1.3)
em-winrm (0.5.4)
erubis (2.7.0)
eventmachine (1.0.0.beta.3)
faraday (0.8.8)
fauxhai (1.1.1)
ffi (1.9.0, 1.8.1)
foodcritic (2.2.0)
gherkin (2.11.8)
git (1.2.5)
gssapi (1.1.2, 1.0.3)
gyoku (1.1.0, 1.0.0)
hashie (2.0.5)
highline (1.6.19)
httparty (0.11.0)
httpclient (2.3.4.1, 2.2.0.2)
httpi (2.1.0, 0.9.7)
i18n (0.6.5, 0.6.4)
interception (0.3)
io-console (0.4.2, 0.3)
ipaddress (0.8.0)
json (1.8.0, 1.7.7, 1.5.4)
knife-windows (0.5.12)
little-plugger (1.1.3)
log4r (1.1.10)
log_switch (0.4.0)
logging (1.8.1, 1.6.2)
method_source (0.8.2)
mime-types (1.24, 1.23)
mini_portile (0.5.1)
minitar (0.5.4)
minitest (5.0.6, 4.7.5, 2.5.1)
minitest-chef-handler (1.0.1)
mixlib-authentication (1.3.0)
mixlib-cli (1.3.0)
mixlib-config (1.1.2)
mixlib-log (1.6.0)
mixlib-shellout (1.2.0)
multi_json (1.7.9)
multi_xml (0.5.5)
multipart-post (1.2.0)
net-http-persistent (2.9)
net-scp (1.1.1, 1.0.4)
net-ssh (2.6.8, 2.6.7, 2.2.2)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.0, 1.1)
nio4r (0.5.0)
nokogiri (1.6.0, 1.5.10)
nori (2.3.0, 1.1.5)
ohai (6.18.0)
polyglot (0.3.3)
pry (0.9.12.2)
pry-doc (0.4.6)
pry-rescue (1.1.1)
pry-stack_explorer (0.4.9.1)
rack (1.5.2)
rake (10.1.0, 10.0.4, 0.9.2.2)
rbzip2 (0.2.0)
rdoc (4.0.1, 3.9.4)
rest-client (1.6.7)
retryable (1.3.3)
ridley (1.5.1, 1.2.5)
rspec (2.14.1)
rspec-core (2.14.5, 2.14.4, 2.12.2)
rspec-expectations (2.14.2, 2.14.1, 2.12.1)
rspec-mocks (2.14.3, 2.12.2)
rubyntlm (0.3.4, 0.1.1)
savon (2.3.0, 0.9.5)
slop (3.4.6)
solve (0.8.0)
strainer (3.2.2)
systemu (2.5.2)
tailor (1.2.1)
term-ansicolor (1.2.2)
text-table (1.2.3)
thor (0.18.1)
thread_safe (0.1.2)
timers (1.1.0)
tins (0.9.0)
treetop (1.4.14)
tzinfo (0.3.37)
uuidtools (2.1.4)
varia_model (0.2.0, 0.1.1)
wasabi (3.2.0, 1.0.0)
winrm (1.1.2)
yajl-ruby (1.1.0)
yard (0.8.7)`

Vagrant settings for the windows box
`config.vm.define :windows_agent do |agent|
    agent.vm.box       = windows_agent_box_name
    agent.vm.box_url   = windows_agent_box_url
    agent.vm.guest     = :windows
  # Admin user name and password
    agent.winrm.username = "vagrant"
    agent.winrm.password = "vagrant"   
    agent.vm.network :private_network, ip: "192.168.250.11" 
    agent.vm.network :forwarded_port, guest: 3389, host: 3390
    agent.vm.network :forwarded_port, guest: 5985, host: 5986
    agent.vm.provision :chef_solo do |chef|
      chef.log_level = "info"
      chef.run_list = [
        "recipe[git]",
      ]
    end
  end`

**Comment by sneal** [comment]
You appear to be using a Vagrant 1.0 compatible Vagrantfile syntax. I would expect this as your first line:

```
Vagrant.configure("2") do |agent|
```

**Comment by pmorton** [comment]
@etxnija  Did this resolve your issue?

**Comment by etxnija** [comment]
@sneal @pmorton 
Sorry for not getting back earlier. The issue stemmed from network settings  and ruby installations on my host machine. I solved it by start using the Ruby install from Chef and update my proxy shell proxy settings by adding no_proxy='127.0.0.1,10._,192.168._ since the guest windoes box tried to go through the proxy to notify vagrant.
