### ISSUE TITLE
Windows Action SetHostName is not stable

### ISSUE THREAD

**Issue by gildas** [WinRb/vagrant-windows#88]
Quite often when vagrant tries to set the hostname in the windows box, there is no change.

As far as I know the wmic command line is not really to be trusted.

Using netdom works all the time.

I should submit a fix soon.

**Comment by gildas** [comment]
BTW, sorry about the pull request. I thought it would grab only my commits, but it also grabbed commits from others.
I closed my pull request and hopefully nothing happened!

**Comment by pmorton** [comment]
@sneal  What do you think of the fix? Is there any indication that the nedtom syntax is the same from Win7/Win2008 on up or is there different syntax depending on your version.

**Comment by sneal** [comment]
It appears the netdom syntax is the same, however it's not always available on the system, i.e. Server 2003, XP, and Win7. I'd like to know a little more about the problem.

**Comment by sneal** [comment]
Closing this for now, at least until we have a better understanding of the problem. wmic has been reliable on Windows Server 2008 R2 for me.

**Comment by gildas** [comment]
Sorry, got caught on other stuff.
I will try again with Windows 2012. And will try to dig a little further.
As for 2003 and XP, I have to apologize, but we do not support these anymore at my company. I understand a lot of people might still use them, though.

**Comment by sneal** [comment]
vagrant-windows doesn't support 2003 or XP either :smile:

**Comment by gildas** [comment]
Ah, ah! So the only one to be nice to is Windows 7.
That said, I would prefer the wmic/powershell version to work on Windows 2012.
After all, Microsoft is killing all their legacy apps one after the other for the cleaner powershell-based approach.
And I like that.
netdom being a legacy app... 
I need to make some progress with my automated lab, so I cannot do the test on a brand new Windows 2012 again soon. But I will give it another try asap. Let's hope it was just me and not Windows 2012.

**Comment by gildas** [comment]
Ok, fun is, I have just upgraded my vagrant to 1.3.5 and the vagrant-windows plugin is now 1.2.1.
Which means I am going to use the wmic version now.
I should be able to give you an update sooner than I thought.

**Comment by ashmere** [comment]
the current wmic command doesn't rename the pc if it is windows 2012 
I notice that from powershell 3.0 onwards you have Rename-Computer cmdlet and netdom is still available could we either get this changed to detect if powershell =>3 use that else stick with the wmic 

or just switch to netdom that I believe works on windows 7 up
